using System.Collections.Generic;

namespace MummyEscape.Core
{
    /// <summary>
    /// GENERATED by tools/LevelLab (dotnet run --project tools/LevelLab -- --bake). Do not edit by hand.
    /// First valid generation attempt of each campaign level, so devices skip the search.
    /// </summary>
    internal static class LevelAttemptTable
    {
        public const int GeneratorVersion = 1;

        static readonly Dictionary<int, int> Attempts = new Dictionary<int, int>
        {
            { 1001, 0 }, // 1-1 par 12
            { 1002, 0 }, // 1-2 par 10
            { 1003, 0 }, // 1-3 par 13
            { 1004, 0 }, // 1-4 par 12
            { 1005, 0 }, // 1-5 par 12
            { 1006, 2 }, // 1-6 par 12
            { 1007, 2 }, // 1-7 par 12
            { 1008, 1 }, // 1-8 par 16
            { 1009, 2 }, // 1-9 par 16
            { 1010, 3 }, // 1-10 par 14
            { 2001, 0 }, // 2-1 par 20
            { 2002, 0 }, // 2-2 par 20
            { 2003, 0 }, // 2-3 par 16
            { 2004, 0 }, // 2-4 par 22
            { 2005, 1 }, // 2-5 par 20
            { 2006, 10 }, // 2-6 par 28
            { 2007, 3 }, // 2-7 par 27
            { 2008, 1 }, // 2-8 par 30
            { 2009, 20 }, // 2-9 par 28
            { 2010, 10 }, // 2-10 par 30
            { 3001, 3 }, // 3-1 par 32
            { 3002, 0 }, // 3-2 par 26
            { 3003, 3 }, // 3-3 par 31
            { 3004, 5 }, // 3-4 par 31
            { 3005, 0 }, // 3-5 par 35
            { 3006, 33 }, // 3-6 par 32
            { 3007, 10 }, // 3-7 par 36
            { 3008, 8 }, // 3-8 par 37
            { 3009, 71 }, // 3-9 par 35
            { 3010, 35 }, // 3-10 par 37
            { 4001, 2 }, // 4-1 par 34
            { 4002, 2 }, // 4-2 par 37
            { 4003, 3 }, // 4-3 par 40
            { 4004, 3 }, // 4-4 par 42
            { 4005, 2 }, // 4-5 par 41
            { 4006, 265 }, // 4-6 par 48
            { 4007, 345 }, // 4-7 par 49
            { 4008, 25 }, // 4-8 par 49
            { 4009, 139 }, // 4-9 par 50
            { 4010, 28 }, // 4-10 par 50
            { 5001, 118 }, // 5-1 par 52
            { 5002, 0 }, // 5-2 par 53
            { 5003, 33 }, // 5-3 par 55
            { 5004, 53 }, // 5-4 par 57
            { 5005, 23 }, // 5-5 par 56
            { 5006, 304 }, // 5-6 par 56
            { 5007, 1301 }, // 5-7 par 57
            { 5008, 301 }, // 5-8 par 55
            { 5009, 199 }, // 5-9 par 60
            { 5010, 50 }, // 5-10 par 57
        };

        public static bool TryGet(LevelId id, out int attempt)
        {
            attempt = 0;
            return GeneratorVersion == DifficultyTable.GeneratorVersion && Attempts.TryGetValue(id.Act * 1000 + id.Index, out attempt);
        }
    }
}
