using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MummyEscape.Core;
using Unity.Services.Authentication;
using Unity.Services.CloudSave;
using Unity.Services.Core;
using Unity.Services.Friends;
using Unity.Services.Friends.Exceptions;
using Unity.Services.Leaderboards;
using UnityEngine;
using CloudPlayer = Unity.Services.CloudSave.Models.Data.Player;

namespace MummyEscape.Online
{
    /// <summary>
    /// Unity Gaming Services backend: anonymous auth, one leaderboard per level (ascending, keep best),
    /// Friends for the social graph and a public Cloud Save key so friends can follow your progression.
    /// Setup: link the project to a UGS project (Edit > Project Settings > Services), then deploy the
    /// leaderboards generated by "Mummy Rush > Online > Export leaderboard configs".
    /// </summary>
    public sealed class UgsOnlineService : IOnlineService
    {
        const string ProgressKey = "progress";

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Register() => OnlineServiceFactory.Create = () => new UgsOnlineService();

        public bool IsAvailable { get; private set; }
        public string PlayerId => IsAvailable ? AuthenticationService.Instance.PlayerId : "";
        public string PlayerName { get; private set; } = "";
        public string Status { get; private set; } = "Connexion…";
        public bool IsDemo => false;
        public string Country { get; set; } = "";

        public async Task InitializeAsync()
        {
            if (string.IsNullOrEmpty(Application.cloudProjectId))
            {
                // Not linked to a UGS project: initializing would only log errors.
                Status = "Hors ligne (projet non lié à Unity Gaming Services)";
                Debug.Log("[Online] Project not linked to UGS (Project Settings > Services), playing offline.");
                return;
            }
            try
            {
                await UnityServices.InitializeAsync();
                // Resumes the cached session (guest or account) or creates a guest player.
                var auth = AuthenticationService.Instance;
                if (!auth.IsSignedIn)
                {
                    // A fresh install (no session on the phone): the Play Games account finds its player again, or makes one.
                    string code = !auth.SessionTokenExists && GoogleSignIn.Supported ? await GoogleSignIn.Provider.GetAuthCodeAsync(false) : null;
                    if (code != null)
                    {
                        try { await auth.SignInWithGooglePlayGamesAsync(code); }
                        catch (Exception e) { Debug.LogWarning("[Online] Google Play Games sign-in failed, playing as a guest: " + e.Message); }
                    }
                    if (!auth.IsSignedIn) await auth.SignInAnonymouslyAsync();
                }
                await AuthenticationService.Instance.GetPlayerInfoAsync();
                PlayerName = await AuthenticationService.Instance.GetPlayerNameAsync();
                await InitFriendsAsync();
                IsAvailable = true;
                Status = "En ligne";
            }
            catch (Exception e)
            {
                IsAvailable = false;
                Status = Loc.F("Hors ligne ({0})", e.Message);
                Debug.LogWarning("[Online] UGS unavailable, playing offline: " + e);
            }
        }

        public async Task<string> SetPlayerNameAsync(string name)
        {
            if (!IsAvailable || string.IsNullOrWhiteSpace(name)) return PlayerName;
            // UGS names cannot contain spaces and get a #1234 suffix appended.
            PlayerName = await AuthenticationService.Instance.UpdatePlayerNameAsync(name.Trim().Replace(' ', '_'));
            return PlayerName;
        }

        public async Task SubmitScoreAsync(LevelResult result)
        {
            if (!IsAvailable || !result.Won) return;
            try
            {
                await LeaderboardsService.Instance.AddPlayerScoreAsync(OnlineServiceFactory.LeaderboardId(result.Level), result.LeaderboardScore,
                    new AddPlayerScoreOptions { Metadata = new ScoreMeta { c = Country ?? "", s = result.Pace == 1 ? 1 : 0 } });
            }
            catch (Exception e) { Debug.LogWarning("[Online] score not submitted: " + e.Message); }
        }

        /// <summary>Score metadata stored with each entry (kept tiny: it is returned for every row).</summary>
        [Serializable]
        /// <summary>c: country; s: 1 when the time is nearly the tomb's perfect minimum on a big maze (suspicious, see TombPace).</summary>
        sealed class ScoreMeta { public string c; public int s; }

        // Country rankings are filtered client-side from the global board (UGS has no per-country boards):
        // walk the best scores page by page until the top N of the country is found.
        const int CountryPageSize = 1000;
        const int CountryMaxPages = 5;

        public async Task<LeaderboardPage> GetLeaderboardAsync(LevelId level, LeaderboardScope scope, int limit)
        {
            var page = new LeaderboardPage();
            if (!IsAvailable) return page;
            string id = OnlineServiceFactory.LeaderboardId(level);
            try
            {
                var lb = LeaderboardsService.Instance;
                if (scope == LeaderboardScope.Global)
                {
                    var res = await lb.GetScoresAsync(id, new GetScoresOptions { Limit = limit, IncludeMetadata = true });
                    foreach (var e in res.Results) page.Rows.Add(ToRow(e, e.Rank + 1));
                }
                else if (scope == LeaderboardScope.Country)
                {
                    for (int p = 0; p < CountryMaxPages && page.Rows.Count < limit; p++)
                    {
                        var res = await lb.GetScoresAsync(id, new GetScoresOptions { Offset = p * CountryPageSize, Limit = CountryPageSize, IncludeMetadata = true });
                        foreach (var e in res.Results)
                            if (CountryOf(e) == Country && page.Rows.Count < limit) page.Rows.Add(ToRow(e, page.Rows.Count + 1));
                        if (res.Results.Count < CountryPageSize) break;
                    }
                }
                else
                {
                    var ids = new List<string> { PlayerId };
                    foreach (var f in Friends) ids.Add(f.Member.Id);
                    var res = await lb.GetScoresByPlayerIdsAsync(id, ids, new GetScoresByPlayerIdsOptions { IncludeMetadata = true });
                    var entries = res.Results;
                    entries.Sort((a, b) => a.Score.CompareTo(b.Score));
                    for (int i = 0; i < entries.Count && i < limit; i++) page.Rows.Add(ToRow(entries[i], i + 1));
                }

                page.Me = page.Rows.Find(r => r.IsMe);
                if (page.Me == null)
                {
                    try
                    {
                        var mine = await lb.GetPlayerScoreAsync(id, new GetPlayerScoreOptions { IncludeMetadata = true });
                        // Global rank is exact; in other scopes we only know the player is outside the fetched top.
                        page.Me = ToRow(mine, scope == LeaderboardScope.Global ? mine.Rank + 1 : 0);
                    }
                    catch (Exception) { /* no score on this level yet */ }
                }
            }
            catch (Exception e) { Debug.LogWarning($"[Online] leaderboard {id}: {e.Message}"); }
            return page;
        }

        LeaderboardRow ToRow(Unity.Services.Leaderboards.Models.LeaderboardEntry e, int rank)
        {
            var (overPar, timeMs) = LevelResult.DecodeScore((long)e.Score);
            return new LeaderboardRow
            {
                Rank = rank,
                PlayerId = e.PlayerId,
                PlayerName = e.PlayerName,
                OverPar = overPar,
                TimeMs = timeMs,
                IsMe = e.PlayerId == PlayerId,
                Country = CountryOf(e),
                Suspicious = MetaOf(e)?.s == 1,
            };
        }

        static ScoreMeta MetaOf(Unity.Services.Leaderboards.Models.LeaderboardEntry e)
        {
            if (string.IsNullOrEmpty(e.Metadata)) return null;
            try { return JsonUtility.FromJson<ScoreMeta>(e.Metadata); }
            catch (Exception) { return null; }
        }

        static string CountryOf(Unity.Services.Leaderboards.Models.LeaderboardEntry e)
        {
            if (string.IsNullOrEmpty(e.Metadata)) return "";
            try { return JsonUtility.FromJson<ScoreMeta>(e.Metadata)?.c ?? ""; }
            catch (Exception) { return ""; }
        }

        public Task<IReadOnlyList<FriendInfo>> GetFriendsAsync()
        {
            var list = new List<FriendInfo>();
            if (IsAvailable)
                foreach (var r in Friends)
                    list.Add(new FriendInfo
                    {
                        PlayerId = r.Member.Id,
                        Name = r.Member.Profile?.Name ?? r.Member.Id,
                        Online = r.Member.Presence != null && r.Member.Presence.Availability == Unity.Services.Friends.Models.Availability.Online,
                    });
            return Task.FromResult<IReadOnlyList<FriendInfo>>(list);
        }

        public Task<IReadOnlyList<FriendRequest>> GetFriendRequestsAsync()
        {
            var list = new List<FriendRequest>();
            if (IsAvailable)
                foreach (var r in FriendRequests)
                    list.Add(new FriendRequest { PlayerId = r.Member.Id, Name = r.Member.Profile?.Name ?? r.Member.Id });
            return Task.FromResult<IReadOnlyList<FriendRequest>>(list);
        }

        public Task<string> SendFriendRequestAsync(string playerName) =>
            string.IsNullOrWhiteSpace(playerName) ? Task.FromResult(NotFound) : RequestFriend(() => FriendsService.Instance.AddFriendByNameAsync(playerName.Trim()));

        public Task<string> SendFriendRequestToIdAsync(string playerId) =>
            string.IsNullOrEmpty(playerId) ? Task.FromResult(NotFound) : RequestFriend(() => FriendsService.Instance.AddFriendAsync(playerId));

        const string NotFound = "Joueur introuvable.";

        async Task<string> RequestFriend(Func<Task> send)
        {
            if (!IsAvailable) return Status;
            if (!_friendsReady) await InitFriendsAsync(); // it could not start with the session: one more try
            if (!_friendsReady) return "La liste d'amis ne répond pas : réessaie dans un instant.";
            try
            {
                await send();
                return null;
            }
            catch (FriendsServiceException e)
            {
                Debug.LogWarning($"[Online] friend request failed: {e.ErrorCode} ({e.StatusCode}) {e.Message}");
                switch (e.ErrorCode)
                {
                    case FriendsErrorCode.UserTargetingSelf: return "C'est ton propre code ami.";
                    case FriendsErrorCode.FriendshipAlreadyExists: return "Vous êtes déjà amis.";
                    case FriendsErrorCode.RelationshipAlreadyExists:
                    case FriendsErrorCode.DuplicateMember: return "Demande déjà envoyée.";
                    case FriendsErrorCode.ActionUnauthorizedWhenBlocked: return "Impossible : l'un de vous a bloqué l'autre.";
                    case FriendsErrorCode.FriendLimitReached:
                    case FriendsErrorCode.FriendRequestLimitReached: return "Tu as atteint le nombre maximum d'amis ou de demandes.";
                    case FriendsErrorCode.TargetsFriendLimitReached: return "Ce joueur a déjà trop d'amis.";
                }
                return e.StatusCode == System.Net.HttpStatusCode.NotFound ? NotFound : Loc.T("Demande impossible pour le moment.") + " (" + (int)e.ErrorCode + ")";
            }
            catch (RequestFailedException e) { return Explain(e, NotFound); }
            catch (Exception e)
            {
                Debug.LogWarning("[Online] friend request failed: " + e.Message);
                return NotFound;
            }
        }

        public async Task AcceptFriendRequestAsync(string playerId)
        {
            if (IsAvailable && _friendsReady) await FriendsService.Instance.AddFriendAsync(playerId);
        }

        public async Task DeclineFriendRequestAsync(string playerId)
        {
            if (IsAvailable && _friendsReady) await FriendsService.Instance.DeleteIncomingFriendRequestAsync(playerId);
        }

        public async Task RemoveFriendAsync(string playerId)
        {
            if (IsAvailable && _friendsReady) await FriendsService.Instance.DeleteFriendAsync(playerId);
        }

        // ================================================================== account

        const string SaveKey = "save";

        public AccountState Account
        {
            get
            {
                if (!IsAvailable || !AuthenticationService.Instance.IsSignedIn) return AccountState.Offline;
                return string.IsNullOrEmpty(Username) ? AccountState.Guest : AccountState.Account;
            }
        }

        /// <summary>The login, or "Google Play Jeux" for an account made with Google only.</summary>
        public string Username => HasPassword ? AuthenticationService.Instance.PlayerInfo.Username : GoogleLinked ? Loc.T("Google Play Jeux") : "";

        public bool HasPassword => IsAvailable && !string.IsNullOrEmpty(AuthenticationService.Instance.PlayerInfo?.Username);

        public bool GoogleLinked => IsAvailable && !string.IsNullOrEmpty(AuthenticationService.Instance.PlayerInfo?.GetGooglePlayGamesId());

        const string NoGoogle = "Connexion à Google Play Jeux annulée ou impossible.";

        public async Task<string> LinkGoogleAsync()
        {
            if (!IsAvailable) return Status;
            if (!GoogleSignIn.Supported) return NoGoogle;
            string code = await GoogleSignIn.Provider.GetAuthCodeAsync(true);
            if (code == null) return NoGoogle;
            try
            {
                // Same player id: progress, scores and friends stay, Google becomes a way back in.
                await AuthenticationService.Instance.LinkWithGooglePlayGamesAsync(code);
                await AuthenticationService.Instance.GetPlayerInfoAsync();
                return null;
            }
            catch (AuthenticationException e) when (e.ErrorCode == AuthenticationErrorCodes.AccountAlreadyLinked)
            {
                return IOnlineService.GoogleTaken;
            }
            catch (RequestFailedException e) { return Explain(e, "Google Play Jeux n'a pas pu être lié à ce joueur."); }
        }

        public async Task<string> SignInWithGoogleAsync()
        {
            if (string.IsNullOrEmpty(Application.cloudProjectId)) return Status;
            if (!GoogleSignIn.Supported) return NoGoogle;
            try
            {
                if (!IsAvailable) await UnityServices.InitializeAsync();
                string code = await GoogleSignIn.Provider.GetAuthCodeAsync(true);
                if (code == null) return NoGoogle;
                var auth = AuthenticationService.Instance;
                // Keep the current session token: if the sign-in fails, the previous player resumes.
                if (auth.IsSignedIn) auth.SignOut(false);
                try
                {
                    await auth.SignInWithGooglePlayGamesAsync(code);
                }
                catch (Exception)
                {
                    if (!auth.IsSignedIn && auth.SessionTokenExists) await auth.SignInAnonymouslyAsync();
                    throw;
                }
                await AfterSignIn();
                return null;
            }
            catch (RequestFailedException e) { return Explain(e, "Connexion à Google Play Jeux impossible."); }
        }

        public async Task<string> CreateAccountAsync(string username, string password)
        {
            if (!IsAvailable) return Status;
            try
            {
                // Links a username/password to the current (anonymous) player: same id, scores and friends.
                await AuthenticationService.Instance.AddUsernamePasswordAsync(username, password);
                await AuthenticationService.Instance.GetPlayerInfoAsync();
                return null;
            }
            catch (AuthenticationException e) when (e.ErrorCode == AuthenticationErrorCodes.AccountAlreadyLinked)
            {
                return "Ce joueur a déjà un compte.";
            }
            catch (RequestFailedException e) { return Explain(e, "Cet identifiant est déjà pris ou invalide."); }
        }

        public async Task<string> SignInAsync(string username, string password)
        {
            if (string.IsNullOrEmpty(Application.cloudProjectId)) return Status;
            try
            {
                if (!IsAvailable) await UnityServices.InitializeAsync();
                var auth = AuthenticationService.Instance;
                // Keep the current session token: if the sign-in fails, the previous player resumes.
                if (auth.IsSignedIn) auth.SignOut(false);
                try
                {
                    await auth.SignInWithUsernamePasswordAsync(username, password);
                }
                catch (Exception)
                {
                    if (!auth.IsSignedIn && auth.SessionTokenExists) await auth.SignInAnonymouslyAsync();
                    throw;
                }
                await AfterSignIn();
                return null;
            }
            catch (RequestFailedException e) { return Explain(e, "Identifiant ou mot de passe incorrect."); }
        }

        async Task AfterSignIn()
        {
            var auth = AuthenticationService.Instance;
            await auth.GetPlayerInfoAsync();
            PlayerName = await auth.GetPlayerNameAsync();
            await InitFriendsAsync();
            IsAvailable = true;
            Status = "En ligne";
        }

        static bool _friendsReady;

        static IReadOnlyList<Unity.Services.Friends.Models.Relationship> Friends =>
            _friendsReady ? FriendsService.Instance.Friends : Array.Empty<Unity.Services.Friends.Models.Relationship>();

        static IReadOnlyList<Unity.Services.Friends.Models.Relationship> FriendRequests =>
            _friendsReady ? FriendsService.Instance.IncomingFriendRequests : Array.Empty<Unity.Services.Friends.Models.Relationship>();

        /// <summary>
        /// Friends right after a sign-out can fail (its live connection still closing: Wire 23002): tried again, then the
        /// game stays online without the friends list rather than going offline.
        /// </summary>
        static async Task InitFriendsAsync()
        {
            _friendsReady = false;
            for (int attempt = 1; ; attempt++)
            {
                try
                {
                    await FriendsService.Instance.InitializeAsync();
                    _friendsReady = true;
                    return;
                }
                catch (Exception e) when (attempt < 3)
                {
                    Debug.LogWarning("[Online] Friends not ready, trying again: " + e.Message);
                    await Task.Delay(1500 * attempt);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[Online] Friends unavailable: " + e.Message);
                    return;
                }
            }
        }

        public Task SignOutAsync()
        {
            if (UnityServices.State == ServicesInitializationState.Initialized && AuthenticationService.Instance.IsSignedIn)
                AuthenticationService.Instance.SignOut(true); // forget the session on this device
            _friendsReady = false;
            IsAvailable = false;
            PlayerName = "";
            Status = "Déconnecté";
            return Task.CompletedTask;
        }

        public async Task<string> ChangePasswordAsync(string current, string next)
        {
            if (!IsAvailable) return Status;
            try
            {
                await AuthenticationService.Instance.UpdatePasswordAsync(current, next);
                return null;
            }
            catch (RequestFailedException e) { return Explain(e, "Mot de passe actuel incorrect."); }
        }

        public async Task<string> DeleteAccountAsync()
        {
            if (!IsAvailable) return Status;
            try
            {
                // Our own data first (Unity also erases a deleted player's data across its services).
                await DeleteKey(SaveKey, false);
                await DeleteKey(ProgressKey, true);
                await DeleteKey("solo_total_stars", false); // duels: the protected PvP data goes with the player
                foreach (var f in new List<Unity.Services.Friends.Models.Relationship>(Friends))
                    try { await FriendsService.Instance.DeleteFriendAsync(f.Member.Id); } catch (Exception) { }
                await AuthenticationService.Instance.DeleteAccountAsync();
                AuthenticationService.Instance.SignOut(true);
                IsAvailable = false;
                PlayerName = "";
                Status = "Compte supprimé";
                return null;
            }
            catch (RequestFailedException e) { return Explain(e, "La suppression a échoué, réessaie plus tard."); }
        }

        static async Task DeleteKey(string key, bool isPublic)
        {
            try
            {
                if (isPublic)
                    await CloudSaveService.Instance.Data.Player.DeleteAsync(key, new CloudPlayer.DeleteOptions(new CloudPlayer.PublicWriteAccessClassOptions()));
                else
                    await CloudSaveService.Instance.Data.Player.DeleteAsync(key, new CloudPlayer.DeleteOptions());
            }
            catch (Exception e) { Debug.Log($"[Online] delete {key}: {e.Message}"); }
        }

        public async Task<string> LoadCloudSaveAsync()
        {
            if (Account != AccountState.Account) return null;
            try
            {
                var items = await CloudSaveService.Instance.Data.Player.LoadAsync(new HashSet<string> { SaveKey });
                return items.TryGetValue(SaveKey, out var item) ? item.Value.GetAsString() : null;
            }
            catch (Exception e) { Debug.LogWarning("[Online] cloud save not loaded: " + e.Message); return null; }
        }

        public async Task SaveCloudSaveAsync(string json)
        {
            if (Account != AccountState.Account) return; // guests keep everything on the device
            try { await CloudSaveService.Instance.Data.Player.SaveAsync(new Dictionary<string, object> { { SaveKey, json } }); }
            catch (Exception e) { Debug.LogWarning("[Online] cloud save not written: " + e.Message); }
        }

        public Task ClearPublishedProgressAsync() => IsAvailable ? DeleteKey(ProgressKey, true) : Task.CompletedTask;

        [Serializable]
        sealed class Export
        {
            public string exportedAtUtc, playerId, playerName, username, account;
            public List<string> friends = new List<string>();
            public List<string> scores = new List<string>();
            public string cloudSave, publicProgress;
        }

        public async Task<string> ExportOnlineDataAsync()
        {
            var x = new Export { exportedAtUtc = DateTime.UtcNow.ToString("o"), account = Account.ToString() };
            if (!IsAvailable) return JsonUtility.ToJson(x, true);
            x.playerId = PlayerId;
            x.playerName = PlayerName;
            x.username = Username;
            foreach (var f in Friends) x.friends.Add($"{f.Member.Profile?.Name ?? f.Member.Id} ({f.Member.Id})");
            foreach (var id in DifficultyTable.AllLevels())
            {
                try
                {
                    var e = await LeaderboardsService.Instance.GetPlayerScoreAsync(OnlineServiceFactory.LeaderboardId(id), new GetPlayerScoreOptions { IncludeMetadata = true });
                    var (overPar, timeMs) = LevelResult.DecodeScore((long)e.Score);
                    x.scores.Add($"{id}: +{overPar} coups, {LevelResult.FormatTime(timeMs)}, rang {e.Rank + 1}, pays « {CountryOf(e)} »"); // noloc: raw data export
                }
                catch (Exception) { /* no score on this level */ }
            }
            try
            {
                var priv = await CloudSaveService.Instance.Data.Player.LoadAsync(new HashSet<string> { SaveKey });
                if (priv.TryGetValue(SaveKey, out var s)) x.cloudSave = s.Value.GetAsString();
                var pub = await CloudSaveService.Instance.Data.Player.LoadAsync(new HashSet<string> { ProgressKey },
                    new CloudPlayer.LoadOptions(new CloudPlayer.PublicReadAccessClassOptions()));
                if (pub.TryGetValue(ProgressKey, out var p)) x.publicProgress = p.Value.GetAsString();
            }
            catch (Exception e) { Debug.LogWarning("[Online] export: " + e.Message); }
            return JsonUtility.ToJson(x, true);
        }

        static string Explain(RequestFailedException e, string fallback)
        {
            Debug.LogWarning($"[Online] {e.ErrorCode}: {e.Message}");
            if (e.ErrorCode == CommonErrorCodes.TransportError || e.ErrorCode == CommonErrorCodes.Timeout || e.ErrorCode == CommonErrorCodes.ServiceUnavailable)
                return "Connexion impossible. Vérifie ton accès à Internet.";
            if (e.ErrorCode == CommonErrorCodes.TooManyRequests) return "Trop de tentatives, réessaie dans quelques minutes.";
            // The service's code, for the support: one message covers several causes.
            return Loc.T(fallback) + " (" + e.ErrorCode + ")";
        }

        public async Task PublishProgressAsync(ProgressSnapshot snapshot)
        {
            if (!IsAvailable) return;
            try
            {
                var data = new Dictionary<string, object> { { ProgressKey, JsonUtility.ToJson(snapshot) } };
                await CloudSaveService.Instance.Data.Player.SaveAsync(data,
                    new CloudPlayer.SaveOptions(new CloudPlayer.PublicWriteAccessClassOptions()));
            }
            catch (Exception e) { Debug.LogWarning("[Online] progress not published: " + e.Message); }
        }

        public async Task<ProgressSnapshot> GetProgressAsync(string playerId)
        {
            if (!IsAvailable) return null;
            try
            {
                var items = await CloudSaveService.Instance.Data.Player.LoadAsync(new HashSet<string> { ProgressKey },
                    new CloudPlayer.LoadOptions(new CloudPlayer.PublicReadAccessClassOptions(playerId)));
                if (items.TryGetValue(ProgressKey, out var item))
                    return JsonUtility.FromJson<ProgressSnapshot>(item.Value.GetAsString());
            }
            catch (Exception e) { Debug.LogWarning("[Online] progress of " + playerId + ": " + e.Message); }
            return null;
        }
    }
}
