using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MummyEscape.Core;
using Unity.Services.Authentication;
using Unity.Services.CloudSave;
using Unity.Services.Core;
using Unity.Services.Friends;
using Unity.Services.Leaderboards;
using UnityEngine;
using CloudPlayer = Unity.Services.CloudSave.Models.Data.Player;

namespace MummyEscape.Online
{
    /// <summary>
    /// Unity Gaming Services backend: anonymous auth, one leaderboard per level (ascending, keep best),
    /// Friends for the social graph and a public Cloud Save key so friends can follow your progression.
    /// Setup: link the project to a UGS project (Edit > Project Settings > Services), then deploy the
    /// leaderboards generated by "Mummy Escape > Online > Export leaderboard configs".
    /// </summary>
    public sealed class UgsOnlineService : IOnlineService
    {
        const string ProgressKey = "progress";

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Register() => OnlineServiceFactory.Create = () => new UgsOnlineService();

        public bool IsAvailable { get; private set; }
        public string PlayerId => IsAvailable ? AuthenticationService.Instance.PlayerId : "";
        public string PlayerName { get; private set; } = "";
        public string Status { get; private set; } = "Connexion…";

        public async Task InitializeAsync()
        {
            try
            {
                await UnityServices.InitializeAsync();
                if (!AuthenticationService.Instance.IsSignedIn) await AuthenticationService.Instance.SignInAnonymouslyAsync();
                PlayerName = await AuthenticationService.Instance.GetPlayerNameAsync();
                await FriendsService.Instance.InitializeAsync();
                IsAvailable = true;
                Status = "En ligne";
            }
            catch (Exception e)
            {
                IsAvailable = false;
                Status = "Hors ligne (" + e.Message + ")";
                Debug.LogWarning("[Online] UGS unavailable, playing offline: " + e);
            }
        }

        public async Task<string> SetPlayerNameAsync(string name)
        {
            if (!IsAvailable || string.IsNullOrWhiteSpace(name)) return PlayerName;
            // UGS names cannot contain spaces and get a #1234 suffix appended.
            PlayerName = await AuthenticationService.Instance.UpdatePlayerNameAsync(name.Trim().Replace(' ', '_'));
            return PlayerName;
        }

        public async Task SubmitScoreAsync(LevelResult result)
        {
            if (!IsAvailable || !result.Won) return;
            try
            {
                await LeaderboardsService.Instance.AddPlayerScoreAsync(OnlineServiceFactory.LeaderboardId(result.Level), result.LeaderboardScore);
            }
            catch (Exception e) { Debug.LogWarning("[Online] score not submitted: " + e.Message); }
        }

        public async Task<IReadOnlyList<LeaderboardRow>> GetLeaderboardAsync(LevelId level, LeaderboardScope scope, int limit)
        {
            var rows = new List<LeaderboardRow>();
            if (!IsAvailable) return rows;
            string id = OnlineServiceFactory.LeaderboardId(level);
            try
            {
                List<Unity.Services.Leaderboards.Models.LeaderboardEntry> entries;
                if (scope == LeaderboardScope.Global)
                {
                    var page = await LeaderboardsService.Instance.GetScoresAsync(id, new GetScoresOptions { Limit = limit });
                    entries = page.Results;
                }
                else
                {
                    var ids = new List<string> { PlayerId };
                    foreach (var f in FriendsService.Instance.Friends) ids.Add(f.Member.Id);
                    var res = await LeaderboardsService.Instance.GetScoresByPlayerIdsAsync(id, ids);
                    entries = res.Results;
                    entries.Sort((a, b) => a.Score.CompareTo(b.Score));
                }

                for (int i = 0; i < entries.Count; i++)
                {
                    var e = entries[i];
                    var (moves, hpLost, interactions) = LevelResult.DecodeScore((long)e.Score);
                    rows.Add(new LeaderboardRow
                    {
                        Rank = scope == LeaderboardScope.Global ? e.Rank + 1 : i + 1,
                        PlayerId = e.PlayerId,
                        PlayerName = e.PlayerName,
                        Moves = moves,
                        HpLost = hpLost,
                        Interactions = interactions,
                        IsMe = e.PlayerId == PlayerId,
                    });
                }
            }
            catch (Exception e) { Debug.LogWarning($"[Online] leaderboard {id}: {e.Message}"); }
            return rows;
        }

        public Task<IReadOnlyList<FriendInfo>> GetFriendsAsync()
        {
            var list = new List<FriendInfo>();
            if (IsAvailable)
                foreach (var r in FriendsService.Instance.Friends)
                    list.Add(new FriendInfo
                    {
                        PlayerId = r.Member.Id,
                        Name = r.Member.Profile?.Name ?? r.Member.Id,
                        Online = r.Member.Presence != null && r.Member.Presence.Availability == Unity.Services.Friends.Models.Availability.Online,
                    });
            return Task.FromResult<IReadOnlyList<FriendInfo>>(list);
        }

        public Task<IReadOnlyList<FriendRequest>> GetFriendRequestsAsync()
        {
            var list = new List<FriendRequest>();
            if (IsAvailable)
                foreach (var r in FriendsService.Instance.IncomingFriendRequests)
                    list.Add(new FriendRequest { PlayerId = r.Member.Id, Name = r.Member.Profile?.Name ?? r.Member.Id });
            return Task.FromResult<IReadOnlyList<FriendRequest>>(list);
        }

        public async Task<bool> SendFriendRequestAsync(string playerName)
        {
            if (!IsAvailable || string.IsNullOrWhiteSpace(playerName)) return false;
            try
            {
                await FriendsService.Instance.AddFriendByNameAsync(playerName.Trim());
                return true;
            }
            catch (Exception e)
            {
                Debug.LogWarning("[Online] friend request failed: " + e.Message);
                return false;
            }
        }

        public async Task AcceptFriendRequestAsync(string playerId)
        {
            if (IsAvailable) await FriendsService.Instance.AddFriendAsync(playerId);
        }

        public async Task RemoveFriendAsync(string playerId)
        {
            if (IsAvailable) await FriendsService.Instance.DeleteFriendAsync(playerId);
        }

        public async Task PublishProgressAsync(ProgressSnapshot snapshot)
        {
            if (!IsAvailable) return;
            try
            {
                var data = new Dictionary<string, object> { { ProgressKey, JsonUtility.ToJson(snapshot) } };
                await CloudSaveService.Instance.Data.Player.SaveAsync(data,
                    new CloudPlayer.SaveOptions(new CloudPlayer.PublicWriteAccessClassOptions()));
            }
            catch (Exception e) { Debug.LogWarning("[Online] progress not published: " + e.Message); }
        }

        public async Task<ProgressSnapshot> GetProgressAsync(string playerId)
        {
            if (!IsAvailable) return null;
            try
            {
                var items = await CloudSaveService.Instance.Data.Player.LoadAsync(new HashSet<string> { ProgressKey },
                    new CloudPlayer.LoadOptions(new CloudPlayer.PublicReadAccessClassOptions(playerId)));
                if (items.TryGetValue(ProgressKey, out var item))
                    return JsonUtility.FromJson<ProgressSnapshot>(item.Value.GetAsString());
            }
            catch (Exception e) { Debug.LogWarning("[Online] progress of " + playerId + ": " + e.Message); }
            return null;
        }
    }
}
