using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MummyEscape.Core;
using Unity.Services.Authentication;
using Unity.Services.CloudSave;
using Unity.Services.Core;
using Unity.Services.Friends;
using Unity.Services.Leaderboards;
using UnityEngine;
using CloudPlayer = Unity.Services.CloudSave.Models.Data.Player;

namespace MummyEscape.Online
{
    /// <summary>
    /// Unity Gaming Services backend: anonymous auth, one leaderboard per level (ascending, keep best),
    /// Friends for the social graph and a public Cloud Save key so friends can follow your progression.
    /// Setup: link the project to a UGS project (Edit > Project Settings > Services), then deploy the
    /// leaderboards generated by "Mummy Escape > Online > Export leaderboard configs".
    /// </summary>
    public sealed class UgsOnlineService : IOnlineService
    {
        const string ProgressKey = "progress";

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Register() => OnlineServiceFactory.Create = () => new UgsOnlineService();

        public bool IsAvailable { get; private set; }
        public string PlayerId => IsAvailable ? AuthenticationService.Instance.PlayerId : "";
        public string PlayerName { get; private set; } = "";
        public string Status { get; private set; } = "Connexion…";
        public bool IsDemo => false;
        public string Country { get; set; } = "";

        public async Task InitializeAsync()
        {
            if (string.IsNullOrEmpty(Application.cloudProjectId))
            {
                // Not linked to a UGS project: initializing would only log errors.
                Status = "Hors ligne (projet non lié à Unity Gaming Services)";
                Debug.Log("[Online] Project not linked to UGS (Project Settings > Services), playing offline.");
                return;
            }
            try
            {
                await UnityServices.InitializeAsync();
                if (!AuthenticationService.Instance.IsSignedIn) await AuthenticationService.Instance.SignInAnonymouslyAsync();
                PlayerName = await AuthenticationService.Instance.GetPlayerNameAsync();
                await FriendsService.Instance.InitializeAsync();
                IsAvailable = true;
                Status = "En ligne";
            }
            catch (Exception e)
            {
                IsAvailable = false;
                Status = "Hors ligne (" + e.Message + ")";
                Debug.LogWarning("[Online] UGS unavailable, playing offline: " + e);
            }
        }

        public async Task<string> SetPlayerNameAsync(string name)
        {
            if (!IsAvailable || string.IsNullOrWhiteSpace(name)) return PlayerName;
            // UGS names cannot contain spaces and get a #1234 suffix appended.
            PlayerName = await AuthenticationService.Instance.UpdatePlayerNameAsync(name.Trim().Replace(' ', '_'));
            return PlayerName;
        }

        public async Task SubmitScoreAsync(LevelResult result)
        {
            if (!IsAvailable || !result.Won) return;
            try
            {
                await LeaderboardsService.Instance.AddPlayerScoreAsync(OnlineServiceFactory.LeaderboardId(result.Level), result.LeaderboardScore,
                    new AddPlayerScoreOptions { Metadata = new ScoreMeta { c = Country ?? "" } });
            }
            catch (Exception e) { Debug.LogWarning("[Online] score not submitted: " + e.Message); }
        }

        /// <summary>Score metadata stored with each entry (kept tiny: it is returned for every row).</summary>
        [Serializable]
        sealed class ScoreMeta { public string c; }

        // Country rankings are filtered client-side from the global board (UGS has no per-country boards):
        // walk the best scores page by page until the top N of the country is found.
        const int CountryPageSize = 1000;
        const int CountryMaxPages = 5;

        public async Task<LeaderboardPage> GetLeaderboardAsync(LevelId level, LeaderboardScope scope, int limit)
        {
            var page = new LeaderboardPage();
            if (!IsAvailable) return page;
            string id = OnlineServiceFactory.LeaderboardId(level);
            try
            {
                var lb = LeaderboardsService.Instance;
                if (scope == LeaderboardScope.Global)
                {
                    var res = await lb.GetScoresAsync(id, new GetScoresOptions { Limit = limit, IncludeMetadata = true });
                    foreach (var e in res.Results) page.Rows.Add(ToRow(e, e.Rank + 1));
                }
                else if (scope == LeaderboardScope.Country)
                {
                    for (int p = 0; p < CountryMaxPages && page.Rows.Count < limit; p++)
                    {
                        var res = await lb.GetScoresAsync(id, new GetScoresOptions { Offset = p * CountryPageSize, Limit = CountryPageSize, IncludeMetadata = true });
                        foreach (var e in res.Results)
                            if (CountryOf(e) == Country && page.Rows.Count < limit) page.Rows.Add(ToRow(e, page.Rows.Count + 1));
                        if (res.Results.Count < CountryPageSize) break;
                    }
                }
                else
                {
                    var ids = new List<string> { PlayerId };
                    foreach (var f in FriendsService.Instance.Friends) ids.Add(f.Member.Id);
                    var res = await lb.GetScoresByPlayerIdsAsync(id, ids, new GetScoresByPlayerIdsOptions { IncludeMetadata = true });
                    var entries = res.Results;
                    entries.Sort((a, b) => a.Score.CompareTo(b.Score));
                    for (int i = 0; i < entries.Count && i < limit; i++) page.Rows.Add(ToRow(entries[i], i + 1));
                }

                page.Me = page.Rows.Find(r => r.IsMe);
                if (page.Me == null)
                {
                    try
                    {
                        var mine = await lb.GetPlayerScoreAsync(id, new GetPlayerScoreOptions { IncludeMetadata = true });
                        // Global rank is exact; in other scopes we only know the player is outside the fetched top.
                        page.Me = ToRow(mine, scope == LeaderboardScope.Global ? mine.Rank + 1 : 0);
                    }
                    catch (Exception) { /* no score on this level yet */ }
                }
            }
            catch (Exception e) { Debug.LogWarning($"[Online] leaderboard {id}: {e.Message}"); }
            return page;
        }

        LeaderboardRow ToRow(Unity.Services.Leaderboards.Models.LeaderboardEntry e, int rank)
        {
            var (overPar, hpLost, interactions) = LevelResult.DecodeScore((long)e.Score);
            return new LeaderboardRow
            {
                Rank = rank,
                PlayerId = e.PlayerId,
                PlayerName = e.PlayerName,
                OverPar = overPar,
                HpLost = hpLost,
                Interactions = interactions,
                IsMe = e.PlayerId == PlayerId,
                Country = CountryOf(e),
            };
        }

        static string CountryOf(Unity.Services.Leaderboards.Models.LeaderboardEntry e)
        {
            if (string.IsNullOrEmpty(e.Metadata)) return "";
            try { return JsonUtility.FromJson<ScoreMeta>(e.Metadata)?.c ?? ""; }
            catch (Exception) { return ""; }
        }

        public Task<IReadOnlyList<FriendInfo>> GetFriendsAsync()
        {
            var list = new List<FriendInfo>();
            if (IsAvailable)
                foreach (var r in FriendsService.Instance.Friends)
                    list.Add(new FriendInfo
                    {
                        PlayerId = r.Member.Id,
                        Name = r.Member.Profile?.Name ?? r.Member.Id,
                        Online = r.Member.Presence != null && r.Member.Presence.Availability == Unity.Services.Friends.Models.Availability.Online,
                    });
            return Task.FromResult<IReadOnlyList<FriendInfo>>(list);
        }

        public Task<IReadOnlyList<FriendRequest>> GetFriendRequestsAsync()
        {
            var list = new List<FriendRequest>();
            if (IsAvailable)
                foreach (var r in FriendsService.Instance.IncomingFriendRequests)
                    list.Add(new FriendRequest { PlayerId = r.Member.Id, Name = r.Member.Profile?.Name ?? r.Member.Id });
            return Task.FromResult<IReadOnlyList<FriendRequest>>(list);
        }

        public async Task<bool> SendFriendRequestAsync(string playerName)
        {
            if (!IsAvailable || string.IsNullOrWhiteSpace(playerName)) return false;
            try
            {
                await FriendsService.Instance.AddFriendByNameAsync(playerName.Trim());
                return true;
            }
            catch (Exception e)
            {
                Debug.LogWarning("[Online] friend request failed: " + e.Message);
                return false;
            }
        }

        public async Task AcceptFriendRequestAsync(string playerId)
        {
            if (IsAvailable) await FriendsService.Instance.AddFriendAsync(playerId);
        }

        public async Task DeclineFriendRequestAsync(string playerId)
        {
            if (IsAvailable) await FriendsService.Instance.DeleteIncomingFriendRequestAsync(playerId);
        }

        public async Task RemoveFriendAsync(string playerId)
        {
            if (IsAvailable) await FriendsService.Instance.DeleteFriendAsync(playerId);
        }

        public async Task PublishProgressAsync(ProgressSnapshot snapshot)
        {
            if (!IsAvailable) return;
            try
            {
                var data = new Dictionary<string, object> { { ProgressKey, JsonUtility.ToJson(snapshot) } };
                await CloudSaveService.Instance.Data.Player.SaveAsync(data,
                    new CloudPlayer.SaveOptions(new CloudPlayer.PublicWriteAccessClassOptions()));
            }
            catch (Exception e) { Debug.LogWarning("[Online] progress not published: " + e.Message); }
        }

        public async Task<ProgressSnapshot> GetProgressAsync(string playerId)
        {
            if (!IsAvailable) return null;
            try
            {
                var items = await CloudSaveService.Instance.Data.Player.LoadAsync(new HashSet<string> { ProgressKey },
                    new CloudPlayer.LoadOptions(new CloudPlayer.PublicReadAccessClassOptions(playerId)));
                if (items.TryGetValue(ProgressKey, out var item))
                    return JsonUtility.FromJson<ProgressSnapshot>(item.Value.GetAsString());
            }
            catch (Exception e) { Debug.LogWarning("[Online] progress of " + playerId + ": " + e.Message); }
            return null;
        }
    }
}
