using System.Collections.Generic;

namespace MummyEscape
{
    public static partial class Loc
    {
        /// <summary>English, keyed by the French text. Placeholders ({0}) and rich-text tags must be kept.</summary>
        static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            // ---------------------------------------------------------------- menu, shop, settings
            ["MUMMY\nESCAPE"] = "MUMMY\nESCAPE",
            ["MUMMY ESCAPE"] = "MUMMY ESCAPE",
            ["Échappe-toi du tombeau… à l'aveugle."] = "Escape the tomb… in the dark.",
            ["JOUER"] = "PLAY",
            ["Classement"] = "Leaderboard",
            ["Amis"] = "Friends",
            ["Boutique"] = "Shop",
            ["Juke-box"] = "Jukebox",
            ["Paramètres"] = "Settings",
            ["Quitter"] = "Quit",
            ["Compte {0} · {1}"] = "Account {0} · {1}",
            ["Invité : {0}"] = "Guest: {0}",
            ["Gagne des scarabées en décrochant de nouvelles étoiles."] = "Earn scarabs by winning new stars.",
            ["{0} scarabées"] = "{0} scarabs",
            ["Équipé"] = "Equipped",
            ["Équiper"] = "Equip",
            ["Son"] = "Sound",
            ["Musique"] = "Music",
            ["Effets sonores"] = "Sound effects",
            ["Image"] = "Display",
            ["Luminosité"] = "Brightness",
            ["normale"] = "normal",
            ["Effets lumineux avancés"] = "Advanced lighting effects",
            ["Tremblements d'écran"] = "Screen shake",
            ["Confort et compte"] = "Comfort and account",
            ["Vibrations"] = "Vibrations",
            ["Aperçu du tombeau au départ"] = "Tomb preview at start",
            ["Mon compte"] = "My account",
            ["Confidentialité"] = "Privacy",
            ["générateur v{0}"] = "generator v{0}",
            ["Langue"] = "Language",
            ["Automatique (langue du téléphone)"] = "Automatic (phone language)",
            ["Langue : automatique ({0})"] = "Language: automatic ({0})",
            ["Langue : {0}"] = "Language: {0}",
            ["Annuler"] = "Cancel",

            // ---------------------------------------------------------------- level select, acts, skins
            ["Choisis ta crypte"] = "Choose your crypt",
            ["Acte {0}"] = "Act {0}",
            ["{0} étage"] = "{0} floor",
            ["{0} étages"] = "{0} floors",
            ["{0} à {1} étages"] = "{0} to {1} floors",
            ["Évadé"] = "Escaped",
            ["Inexploré"] = "Unexplored",
            ["L'Antichambre"] = "The Antechamber",
            ["Les Galeries inondées"] = "The Flooded Galleries",
            ["Les Ruines effondrées"] = "The Collapsed Ruins",
            ["La Cité d'Anubis"] = "The City of Anubis",
            ["Le Sanctuaire embrasé"] = "The Blazing Sanctuary",
            ["Un tombeau intact, scellé depuis trois mille ans."] = "An untouched tomb, sealed for three thousand years.",
            ["Le Nil a envahi les galeries : les courants emportent tout."] = "The Nile has flooded the galleries: the currents sweep everything away.",
            ["Les voûtes s'effondrent : chaque dalle peut céder."] = "The vaults are collapsing: any slab may give way.",
            ["Une cité d'Anubis venue d'un autre âge : lasers et portails."] = "A city of Anubis from another age: lasers and portals.",
            ["Le sanctuaire brûle : les flammes jaillissent en rythme."] = "The sanctuary is burning: flames burst out in rhythm.",
            ["Momie du Nil"] = "Nile Mummy",
            ["Pharaon doré"] = "Golden Pharaoh",
            ["Ombre d'Anubis"] = "Shadow of Anubis",
            ["Momie de jade"] = "Jade Mummy",
            ["Gardien lapis"] = "Lapis Guardian",
            ["Scarabée sacré"] = "Sacred Scarab",
            ["Momie classique"] = "Classic Mummy",
            ["Momie de Bastet"] = "Bastet Mummy",
            ["Momie chacal"] = "Jackal Mummy",
            ["Momie aux hiéroglyphes"] = "Hieroglyph Mummy",
            ["Momie des marais"] = "Swamp Mummy",
            ["Momie de pierre"] = "Stone Mummy",
            ["Momie cybernétique"] = "Cyber Mummy",
            ["Momie de braise"] = "Ember Mummy",
            ["Torche de bois"] = "Wooden Torch",
            ["Sceptre d'or"] = "Golden Scepter",
            ["Lanterne de nacre"] = "Pearl Lantern",
            ["Torche d'os"] = "Bone Torch",
            ["Torche à plasma"] = "Plasma Torch",
            ["Torche d'obsidienne"] = "Obsidian Torch",
            ["Tête nue"] = "Bare Head",
            ["Casque d'explorateur"] = "Explorer's Helmet",
            ["Némès du pharaon"] = "Pharaoh's Nemes",
            ["Couronne de lotus"] = "Lotus Crown",
            ["Heaume de bronze brisé"] = "Broken Bronze Helm",
            ["Oreilles d'Anubis"] = "Anubis Ears",
            ["Disque de Râ"] = "Sun Disk of Ra",
            ["Pieds bandés"] = "Bandaged Feet",
            ["Babouches"] = "Slippers",
            ["Sandales dorées"] = "Golden Sandals",
            ["Bottes de vase"] = "Mud Boots",
            ["Bottes de pierre"] = "Stone Boots",
            ["Bottes à réacteurs"] = "Jet Boots",
            ["Sabots d'obsidienne"] = "Obsidian Hooves",
            ["Thèmes"] = "Themes",
            ["Momies"] = "Mummies",
            ["Couleurs"] = "Colors",
            ["Torches"] = "Torches",
            ["Chapeaux"] = "Hats",
            ["Pieds"] = "Feet",
            ["Classique"] = "Classic",
            ["Tout équiper"] = "Equip all",
            ["Ensemble : {0} scarabées"] = "Set: {0} scarabs",
            ["Chaque acte a sa collection : momie, torche, chapeau et chaussures, débloquée par tes étoiles (25 par acte). L'ensemble complet coûte 20 % de moins."] =
                "Each act has its collection: mummy, torch, hat and shoes, unlocked by your stars (25 per act). The full set costs 20% less.",
            ["Les étoiles débloquent les collections des actes, les scarabées les paient."] = "Stars unlock the act collections, scarabs pay for them.",
            ["{0} étoiles requises"] = "{0} stars needed",
            ["Débloqué à {0} étoiles"] = "Unlocks at {0} stars",

            // ---------------------------------------------------------------- in game
            ["Carte"] = "Map",
            ["Désamorcer"] = "Disarm",
            ["Prêt"] = "Ready",
            ["À toi de jouer"] = "Your turn",
            ["Coups"] = "Moves",
            ["Temps"] = "Time",
            ["Interactions"] = "Interactions",
            ["Vie"] = "Life",
            ["Coups · idéal {0}"] = "Moves · ideal {0}",
            ["Réessayer"] = "Try again",
            ["Les pièges ont eu raison de toi."] = "The traps got the better of you.",
            ["Menus"] = "Menus",
            ["Étage {0}"] = "Floor {0}",
            ["propre à l'étage"] = "this floor only",
            ["tout l'acte"] = "whole act",
            ["Boucle d'ambiance intégrée"] = "Built-in ambient loop",
            ["Thème composé par le jeu"] = "Theme composed by the game",
            ["Musiques dans Resources/Music : act2 (tout l'acte), act2_f2 (étage 2), act2_b (variante, tirée au hasard)."] = "Music in Resources/Music: act2 (whole act), act2_f2 (floor 2), act2_b (variant, drawn at random).",
            ["Étage suivant"] = "Next floor",
            ["Niveau {0}"] = "Level {0}",
            ["Les dieux scellent un nouveau tombeau…"] = "The gods are sealing a new tomb…",
            ["Coups : {0}"] = "Moves: {0}",
            ["à battre {0}"] = "to beat {0}",
            ["Momie experte battue ! ({0})"] = "Expert mummy beaten! ({0})",
            ["Momie experte : {0}"] = "Expert mummy: {0}",
            ["Étage {0} / {1}"] = "Floor {0} / {1}",
            ["Acte {0} — {1}"] = "Act {0} — {1}",
            ["Mémorise le tombeau !"] = "Memorize the tomb!",
            ["Enregistrement d'écran détecté :\nle tombeau reste dans l'ombre"] = "Screen recording detected:\nthe tomb stays in the dark",
            ["Capture d'écran : les dieux ont scellé\nun autre tombeau !"] = "Screenshot: the gods have sealed\nanother tomb!",
            ["Aveuglé ! ({0})"] = "Blinded! ({0})",
            ["Commandes inversées ! ({0})"] = "Controls reversed! ({0})",
            ["Le tombeau a pivoté !\nTes gestes suivent l'écran."] = "The tomb has turned!\nYour swipes follow the screen.",
            ["Torche éteinte : longe une torche murale"] = "Torch out: walk past a wall torch",
            ["Glisse pour avancer d'une case.\nTa torche éclaire les cases voisines."] = "Swipe to move one tile.\nYour torch lights up the tiles around you.",
            ["Maintiens « Carte » pour revoir ce que tu as exploré."] = "Hold \"Map\" to review what you have explored.",
            ["Les courants t'emportent jusqu'au bout\net ne se remontent pas."] = "Currents carry you all the way\nand cannot be walked against.",
            ["Les dalles fissurées s'effondrent\ndès que tu les quittes."] = "Cracked slabs collapse\nas soon as you step off them.",
            ["Un levier inverse les barrières :\nrouges ouvertes, bleues fermées."] = "A lever swaps the barriers:\nred open, blue closed.",
            ["Les jets de flammes crachent un pas sur trois :\nobserve leur rythme."] = "Flame jets fire every third step:\nwatch their rhythm.",
            ["Pause"] = "Pause",
            ["Reprendre"] = "Resume",
            ["Recommencer"] = "Restart",
            ["Quitter le niveau"] = "Quit level",

            // ---------------------------------------------------------------- end of level, scores
            ["ÉVADÉ !"] = "ESCAPED!",
            ["EMMURÉE !"] = "WALLED IN!",
            ["LA MOMIE A PÉRI"] = "THE MUMMY PERISHED",
            ["Chemin parfait !"] = "Perfect path!",
            ["Excellent !"] = "Excellent!",
            ["Bien joué !"] = "Well played!",
            ["Évadée de justesse !"] = "A narrow escape!",
            ["chemin idéal : {0} coups"] = "ideal path: {0} moves",
            ["{0} coups ou moins pour l'étoile suivante"] = "{0} moves or fewer for the next star",
            ["Courants, dalles effondrées et barrières ne pardonnent pas."] = "Currents, collapsed slabs and barriers are unforgiving.",
            ["Nouveau record ! ({0} → {1})"] = "New record! ({0} → {1})",
            ["Premier passage !"] = "First clear!",
            ["+{0} scarabées"] = "+{0} scarabs",
            ["Partager"] = "Share",
            ["Niveau suivant"] = "Next level",
            ["Rejouer"] = "Play again",
            ["Menu"] = "Menu",
            ["parfait"] = "perfect",
            ["+{0} coup"] = "+{0} move",
            ["+{0} coups"] = "+{0} moves",
            ["Évadé en {0} coups, {1} ({2})"] = "Escaped in {0} moves, {1} ({2})",
            ["{0} interactions · {1}/{2} PV restants"] = "{0} interactions · {1}/{2} HP left",
            ["Feras-tu mieux ? {0}"] = "Can you do better? {0}",
            ["Partager mon évasion"] = "Share my escape",

            // ---------------------------------------------------------------- leaderboard
            ["Monde"] = "World",
            ["Pays"] = "Country",
            ["Chargement…"] = "Loading…",
            ["Choisis ton pays dans Amis › Profil."] = "Choose your country in Friends › Profile.",
            ["Top 100 mondial"] = "Global top 100",
            ["Top 100 · {0}"] = "Top 100 · {0}",
            ["Toi et tes amis"] = "You and your friends",
            ["démo hors ligne"] = "offline demo",
            ["hors ligne"] = "offline",
            ["{0}  (toi)"] = "{0}  (you)",
            ["Ton record : {0} (pas encore classé)"] = "Your record: {0} (not ranked yet)",
            ["Termine ce niveau pour entrer au classement"] = "Finish this level to enter the leaderboard",

            // ---------------------------------------------------------------- friends
            ["Mon nom"] = "My name",
            ["Demandes"] = "Requests",
            ["+  Ajouter un ami"] = "+  Add a friend",
            ["Ton code ami : donne-le à tes amis"] = "Your friend code: give it to your friends",
            ["Démo hors ligne (amis fictifs)"] = "Offline demo (fictional friends)",
            ["Hors ligne"] = "Offline",
            ["Pays ?"] = "Country?",
            ["Pays : {0}"] = "Country: {0}",
            ["Les amis font partie du mode en ligne : Paramètres › Confidentialité."] = "Friends are part of online mode: Settings › Privacy.",
            ["Amis ({0})"] = "Friends ({0})",
            ["Demandes ({0})"] = "Requests ({0})",
            ["Aucun ami pour l'instant.\nPartage ton code pour qu'on t'ajoute !"] = "No friends yet.\nShare your code so people can add you!",
            ["Aucune demande en attente."] = "No pending requests.",
            ["En ligne"] = "Online",
            ["progression non partagée"] = "progress not shared",
            ["niveau {0} · {1} étoiles"] = "level {0} · {1} stars",
            ["veut devenir ton ami"] = "wants to be your friend",
            ["Refuser"] = "Decline",
            ["Accepter"] = "Accept",
            ["Ton nom de momie"] = "Your mummy name",
            ["Visible dans les classements.\nN'utilise pas ton vrai nom."] = "Shown in the leaderboards.\nDon't use your real name.",
            ["Nom"] = "Name",
            ["Enregistrer"] = "Save",
            ["3 caractères minimum."] = "3 characters minimum.",
            ["Ajouter un ami"] = "Add a friend",
            ["Demande-lui son code ami\n(exemple : Nefertari#2041)."] = "Ask for their friend code\n(example: Nefertari#2041).",
            ["Code ami"] = "Friend code",
            ["Inviter"] = "Invite",
            ["Le code contient un # suivi de 4 chiffres."] = "The code contains a # followed by 4 digits.",
            ["Joueur introuvable."] = "Player not found.",
            ["Ajoute-moi sur Mummy Escape ! Mon code ami : {0}"] = "Add me on Mummy Escape! My friend code: {0}",
            ["le plus loin"] = "furthest",
            ["étoiles"] = "stars",
            ["Niveau"] = "Level",
            ["Ami"] = "Friend",
            ["Toi"] = "You",
            ["/ toi {0}"] = "/ you {0}",
            ["Retirer des amis"] = "Remove friend",
            ["Progression non partagée pour l'instant."] = "Progress not shared yet.",
            ["Confirmer le retrait ?"] = "Confirm removal?",
            ["Momie"] = "Mummy",

            // ---------------------------------------------------------------- country
            ["Ton pays"] = "Your country",
            ["Affiché à côté de tes scores et utilisé pour le classement « Pays ».\nFacultatif : tu peux le retirer à tout moment."] =
                "Shown next to your scores and used for the \"Country\" leaderboard.\nOptional: you can remove it at any time.",
            ["Ne pas afficher"] = "Don't show",
            ["par défaut"] = "default",
            ["Pays de l'appareil"] = "Device country",
            ["inconnu"] = "unknown",
            ["Inconnu"] = "Unknown",
            ["Afrique du Sud"] = "South Africa", ["Algérie"] = "Algeria", ["Allemagne"] = "Germany",
            ["Arabie saoudite"] = "Saudi Arabia", ["Argentine"] = "Argentina", ["Australie"] = "Australia",
            ["Autriche"] = "Austria", ["Belgique"] = "Belgium", ["Bénin"] = "Benin",
            ["Brésil"] = "Brazil", ["Burkina Faso"] = "Burkina Faso", ["Cameroun"] = "Cameroon",
            ["Canada"] = "Canada", ["Chili"] = "Chile", ["Chine"] = "China",
            ["Colombie"] = "Colombia", ["Corée du Sud"] = "South Korea", ["Côte d'Ivoire"] = "Côte d'Ivoire",
            ["Danemark"] = "Denmark", ["Égypte"] = "Egypt", ["Émirats arabes unis"] = "United Arab Emirates",
            ["Espagne"] = "Spain", ["États-Unis"] = "United States", ["Finlande"] = "Finland",
            ["France"] = "France", ["Gabon"] = "Gabon", ["Grèce"] = "Greece",
            ["Haïti"] = "Haiti", ["Hongrie"] = "Hungary", ["Inde"] = "India",
            ["Indonésie"] = "Indonesia", ["Irlande"] = "Ireland", ["Israël"] = "Israel",
            ["Italie"] = "Italy", ["Japon"] = "Japan", ["Liban"] = "Lebanon",
            ["Luxembourg"] = "Luxembourg", ["Madagascar"] = "Madagascar", ["Mali"] = "Mali",
            ["Maroc"] = "Morocco", ["Mexique"] = "Mexico", ["Monaco"] = "Monaco",
            ["Norvège"] = "Norway", ["Nouvelle-Zélande"] = "New Zealand", ["Pays-Bas"] = "Netherlands",
            ["Pérou"] = "Peru", ["Philippines"] = "Philippines", ["Pologne"] = "Poland",
            ["Portugal"] = "Portugal", ["RD Congo"] = "DR Congo", ["Roumanie"] = "Romania",
            ["Royaume-Uni"] = "United Kingdom", ["Sénégal"] = "Senegal", ["Suède"] = "Sweden",
            ["Suisse"] = "Switzerland", ["Thaïlande"] = "Thailand", ["Tunisie"] = "Tunisia",
            ["Turquie"] = "Turkey", ["Ukraine"] = "Ukraine", ["Viêt Nam"] = "Vietnam",

            // ---------------------------------------------------------------- first launch, privacy
            ["Conditions"] = "Terms",
            ["Avant de jouer"] = "Before you play",
            ["Mummy Escape se joue sans connexion : dans ce mode, rien ne quitte ton téléphone.\n\n" +
             "Le mode en ligne ajoute les classements, les amis et un compte facultatif pour retrouver ta progression sur un autre appareil. " +
             "Il envoie alors à notre prestataire (Unity) un identifiant aléatoire, ton pseudonyme et tes scores.\n\n" +
             "Ni publicité, ni pistage, ni adresse e-mail."] =
                "Mummy Escape can be played without a connection: in that mode, nothing leaves your phone.\n\n" +
                "Online mode adds leaderboards, friends and an optional account to restore your progress on another device. " +
                "It then sends our provider (Unity) a random ID, your nickname and your scores.\n\n" +
                "No ads, no tracking, no email address.",
            ["Jouer en ligne"] = "Play online",
            ["Jouer hors ligne"] = "Play offline",
            ["Tu peux changer d'avis à tout moment dans Paramètres › Confidentialité."] = "You can change your mind at any time in Settings › Privacy.",
            ["Ton année de naissance"] = "Your year of birth",
            ["Elle sert seulement à savoir si l'accord d'un parent est nécessaire. Elle n'est ni conservée, ni envoyée."] =
                "It is only used to know whether a parent's consent is needed. It is neither kept nor sent.",
            ["AAAA"] = "YYYY",
            ["J'accepte les conditions d'utilisation"] = "I accept the terms of use",
            ["Lire les conditions"] = "Read the terms",
            ["Lire la confidentialité"] = "Read the privacy policy",
            ["Retour"] = "Back",
            ["Continuer"] = "Continue",
            ["Indique une année valide (4 chiffres)."] = "Enter a valid year (4 digits).",
            ["Accepte les conditions pour jouer en ligne."] = "Accept the terms to play online.",
            ["Demande à un parent"] = "Ask a parent",
            ["Pour jouer en ligne à ton âge, l'accord d'un parent ou d'un tuteur est nécessaire.\n\n" +
             "À l'attention du parent : le mode en ligne publie un pseudonyme (attribué au hasard, modifiable) et les scores de votre enfant, " +
             "et lui permet d'ajouter des amis par leur code. Aucune adresse e-mail, aucun nom réel, aucune publicité. " +
             "Vous pouvez retirer cet accord et supprimer ses données à tout moment dans Paramètres › Confidentialité."] =
                "To play online at your age, a parent's or guardian's consent is required.\n\n" +
                "For the parent: online mode publishes a nickname (randomly assigned, editable) and your child's scores, " +
                "and lets them add friends by their code. No email address, no real name, no ads. " +
                "You can withdraw this consent and delete their data at any time in Settings › Privacy.",
            ["Lire la politique de confidentialité"] = "Read the privacy policy",
            ["Parent ou tuteur : votre année de naissance"] = "Parent or guardian: your year of birth",
            ["Je suis son parent ou tuteur et j'autorise"] = "I am their parent or guardian and I consent",
            ["Autoriser"] = "Allow",
            ["L'accord doit venir d'un adulte."] = "Consent must come from an adult.",
            ["Cochez la case pour confirmer votre accord."] = "Tick the box to confirm your consent.",
            ["Mode en ligne"] = "Online mode",
            ["Classements, amis, compte"] = "Leaderboards, friends, account",
            ["État : en ligne ({0})"] = "Status: online ({0})",
            ["État : {0}"] = "Status: {0}",
            ["Retirer l'autorisation parentale"] = "Withdraw parental consent",
            ["Mes amis voient ma progression"] = "My friends see my progress",
            ["non affiché"] = "not shown",
            ["celui de l'appareil"] = "the device's",
            ["Pays dans les classements : {0}"] = "Country in leaderboards: {0}",
            ["Mes données"] = "My data",
            ["Exporter mes données"] = "Export my data",
            ["Supprimer mes données en ligne"] = "Delete my online data",
            ["Effacer les données de ce téléphone"] = "Erase the data on this phone",
            ["Informations"] = "Information",
            ["Ni publicité, ni mesure d'audience, ni traceur, ni adresse e-mail."] = "No ads, no analytics, no trackers, no email address.",
            ["Politique de confidentialité"] = "Privacy policy",
            ["Conditions d'utilisation"] = "Terms of use",
            ["Contacter l'éditeur"] = "Contact the publisher",
            ["Une réclamation ? Tu peux saisir la CNIL (cnil.fr) ou l'autorité de ton pays."] =
                "A complaint? You can contact the CNIL (cnil.fr) or the authority of your country.",
            ["Ton dernier choix : {0} (politique v{1})."] = "Your last choice: {0} (policy v{1}).",
            ["compte {0}"] = "account {0}",
            ["invité"] = "guest",
            ["Supprimer mes données en ligne ?"] = "Delete my online data?",
            ["Ton profil, ton compte, ton pseudonyme, tes scores, tes amis et ta sauvegarde en ligne seront définitivement effacés. " +
             "Le mode en ligne sera désactivé. Ta progression sur ce téléphone est conservée."] =
                "Your profile, account, nickname, scores, friends and online backup will be permanently erased. " +
                "Online mode will be turned off. Your progress on this phone is kept.",
            ["Supprimer"] = "Delete",
            ["Effacer ce téléphone ?"] = "Erase this phone?",
            ["Ta progression, tes scarabées, tes apparences et tes choix enregistrés sur ce téléphone seront effacés. " +
             "Tes données en ligne ne sont pas touchées (supprime-les d'abord si tu le souhaites)."] =
                "Your progress, scarabs, skins and choices saved on this phone will be erased. " +
                "Your online data is not affected (delete it first if you wish).",
            ["Effacer"] = "Erase",

            // ---------------------------------------------------------------- account
            ["Compte"] = "Account",
            ["Mode hors ligne"] = "Offline mode",
            ["Le compte fait partie du mode en ligne. Active-le dans Confidentialité pour créer un compte ou te connecter."] =
                "The account is part of online mode. Turn it on in Privacy to create an account or sign in.",
            ["Connecté"] = "Signed in",
            ["Identifiant : {0}\nPseudonyme public : {1}"] = "Login: {0}\nPublic nickname: {1}",
            ["Ta progression est sauvegardée en ligne : connecte-toi avec ce compte sur un autre appareil pour la retrouver."] =
                "Your progress is backed up online: sign in with this account on another device to get it back.",
            ["Changer le mot de passe"] = "Change password",
            ["Se déconnecter"] = "Sign out",
            ["Supprimer mon compte"] = "Delete my account",
            ["Tu joues en invité"] = "You are playing as a guest",
            ["Ta progression n'existe que sur ce téléphone. Crée un compte pour la sauvegarder et la retrouver ailleurs : " +
             "il suffit d'un identifiant et d'un mot de passe, sans adresse e-mail."] =
                "Your progress only exists on this phone. Create an account to back it up and find it elsewhere: " +
                "all it takes is a login and a password, no email address.",
            ["Créer un compte"] = "Create an account",
            ["Non connecté"] = "Not signed in",
            ["Continuer en invité"] = "Continue as a guest",
            ["J'ai déjà un compte"] = "I already have an account",
            ["Sans e-mail, un mot de passe oublié ne peut pas être récupéré : note-le bien."] =
                "Without an email, a forgotten password cannot be recovered: write it down.",
            ["Identifiant : {0}-{1} caractères (lettres, chiffres, . - _ @)."] = "Login: {0}-{1} characters (letters, digits, . - _ @).",
            ["Mot de passe : {0}-{1} caractères, majuscule, minuscule, chiffre et symbole."] =
                "Password: {0}-{1} characters, uppercase, lowercase, digit and symbol.",
            ["Identifiant"] = "Login",
            ["Mot de passe"] = "Password",
            ["Confirme le mot de passe"] = "Confirm the password",
            ["Créer"] = "Create",
            ["Les deux mots de passe diffèrent."] = "The two passwords don't match.",
            ["Se connecter"] = "Sign in",
            ["La progression de ce téléphone sera ajoutée à celle du compte."] = "This phone's progress will be added to the account's.",
            ["Connexion"] = "Sign in",
            ["Remplis les deux champs."] = "Fill in both fields.",
            ["Mot de passe actuel"] = "Current password",
            ["Nouveau mot de passe"] = "New password",
            ["Confirme le nouveau"] = "Confirm the new one",
            ["Changer"] = "Change",
            ["Identifiant : {0} à {1} caractères."] = "Login: {0} to {1} characters.",
            ["Identifiant : lettres, chiffres et . - _ @ uniquement (sans accents ni espaces)."] =
                "Login: letters, digits and . - _ @ only (no accents or spaces).",
            ["Mot de passe : {0} à {1} caractères."] = "Password: {0} to {1} characters.",
            ["Mot de passe : au moins une majuscule, une minuscule, un chiffre et un symbole."] =
                "Password: at least one uppercase letter, one lowercase letter, one digit and one symbol.",

            // ---------------------------------------------------------------- online statuses and errors
            ["Hors ligne (autorisation parentale requise pour jouer en ligne)"] = "Offline (parental consent required to play online)",
            ["Hors ligne (mode en ligne désactivé dans Confidentialité)"] = "Offline (online mode turned off in Privacy)",
            ["Déconnecté (Paramètres › Compte pour te reconnecter)"] = "Signed out (Settings › Account to sign back in)",
            ["Connexion impossible : {0}"] = "Cannot connect: {0}",
            ["Données en ligne supprimées — mode hors ligne"] = "Online data deleted — offline mode",
            ["Hors ligne — configure Unity Gaming Services pour les classements et les amis."] =
                "Offline — set up Unity Gaming Services for leaderboards and friends.",
            ["Les comptes nécessitent une connexion à Unity Gaming Services."] = "Accounts require a connection to Unity Gaming Services.",
            ["Identifiant ou mot de passe incorrect."] = "Wrong login or password.",
            ["Mot de passe actuel incorrect."] = "Wrong current password.",
            ["Connexion…"] = "Connecting…",
            ["Hors ligne (projet non lié à Unity Gaming Services)"] = "Offline (project not linked to Unity Gaming Services)",
            ["Hors ligne ({0})"] = "Offline ({0})",
            ["Ce joueur a déjà un compte."] = "This player already has an account.",
            ["Cet identifiant est déjà pris ou invalide."] = "This login is already taken or invalid.",
            ["Déconnecté"] = "Signed out",
            ["Compte supprimé"] = "Account deleted",
            ["La suppression a échoué, réessaie plus tard."] = "Deletion failed, try again later.",
            ["Connexion impossible. Vérifie ton accès à Internet."] = "Cannot connect. Check your Internet access.",
            ["Trop de tentatives, réessaie dans quelques minutes."] = "Too many attempts, try again in a few minutes.",

            // ---- Duels (PvP)
            ["Duel"] = "Duel",
            ["Duel contre {0}"] = "Duel against {0}",
            ["Chercher un adversaire"] = "Find an opponent",
            ["Recherche d'un adversaire…"] = "Finding an opponent…",
            ["Même tombeau pour les deux : le fantôme d'un joueur de ton niveau court à tes côtés. 3 minutes, le premier sorti gagne ; sinon, celui qui est allé le plus loin."] = "Same tomb for both: the ghost of a player of your level runs beside you. 3 minutes, first one out wins; otherwise, whoever got furthest.",
            ["Classement mensuel"] = "Monthly ranking",
            ["Récompenses"] = "Rewards",
            ["Récompenses de {0}"] = "{0} rewards",
            ["Boutique des sceaux"] = "Seal shop",
            ["Les sceaux de Maât se gagnent en duel (1re victoire du jour, coffre quotidien). Chaque article demande d'avoir atteint sa ligue."] = "Seals of Maat are earned in duels (first win of the day, daily chest). Each item requires reaching its league.",
            ["Les duels se jouent en ligne : active le mode en ligne (Paramètres › Confidentialité)."] = "Duels are played online: turn online mode on (Settings › Privacy).",
            ["Connexion au serveur des duels impossible."] = "Cannot reach the duel server.",
            ["Démo hors ligne : adversaires simulés"] = "Offline demo: simulated opponents",
            ["Top 100"] = "Top 100",
            ["Ligue {0}"] = "{0} league",
            ["Bronze"] = "Bronze",
            ["Argent"] = "Silver",
            ["Or"] = "Gold",
            ["Platine"] = "Platinum",
            ["Diamant"] = "Diamond",
            ["Elo {0} · {1} · {2}e mondial"] = "Elo {0} · {1} · world #{2}",
            ["Elo {0} · {1}e mondial"] = "Elo {0} · world #{1}",
            ["Elo {0} · pas encore classé ce mois-ci"] = "Elo {0} · not ranked yet this month",
            ["{0} victoire"] = "{0} win",
            ["{0} victoires"] = "{0} wins",
            ["{0} nul"] = "{0} draw",
            ["{0} nuls"] = "{0} draws",
            ["{0} défaite"] = "{0} loss",
            ["{0} défaites"] = "{0} losses",
            ["{0} duel"] = "{0} duel",
            ["{0} duels"] = "{0} duels",
            ["placement {0}/{1}"] = "placement {0}/{1}",
            ["torche de saison {0}/{1}"] = "season torch {0}/{1}",
            ["coffre du jour à gagner"] = "daily chest to win",
            ["{0} étoiles en solo pour débloquer ({1}/{0})"] = "{0} solo stars to unlock ({1}/{0})",
            ["Débloqué (ligue {0})"] = "Unlocked ({0} league)",
            ["Atteins la ligue {0} pour l'acheter"] = "Reach the {0} league to buy it",
            ["{0} sceaux"] = "{0} seals",
            ["{0} : à toi !"] = "{0}: it's yours!",
            ["Débloqué : {0}"] = "Unlocked: {0}",
            ["À porter depuis la Boutique"] = "Wear it from the Shop",
            ["Pas de récompense pour {0} : il fallait {1} duels (dont {2} la dernière semaine), ou {3} duels comptés pour la torche."] = "No reward for {0}: it took {1} duels ({2} in the last week), or {3} counted duels for the torch.",
            ["Gagne {0} étoiles en solo pour débloquer les duels."] = "Win {0} solo stars to unlock duels.",
            ["Mets le jeu à jour pour affronter les autres joueurs."] = "Update the game to face other players.",
            ["Pas assez de sceaux."] = "Not enough seals.",
            ["Atteins d'abord la ligue demandée."] = "Reach the required league first.",
            ["Tu l'as déjà."] = "You already own it.",
            ["Rien à récupérer pour le moment."] = "Nothing to collect for now.",
            ["Course refusée par le serveur : comptée comme un abandon."] = "Run rejected by the server: counted as a forfeit.",
            ["Ce duel a expiré (plus de 10 minutes) : il compte comme un abandon."] = "This duel expired (over 10 minutes): it counts as a forfeit.",
            ["Classement des duels"] = "Duel ranking",
            ["Ce mois-ci"] = "This month",
            ["Mois dernier"] = "Last month",
            ["Classement disponible en ligne uniquement."] = "Ranking available online only.",
            ["Aucun classement archivé pour le moment."] = "No archived ranking yet.",
            ["Top 100 · {0} (remise à zéro le 1er du mois)"] = "Top 100 · {0} (resets on the 1st)",
            ["Classement final · {0}"] = "Final standings · {0}",
            ["Joue un duel pour entrer au classement du mois"] = "Play a duel to enter this month's ranking",
            ["Pas classé ce mois-là"] = "Not ranked that month",
            ["Pas de rival : tu ouvres la voie"] = "No rival: you lead the way",
            ["sorti en {0}"] = "out in {0}",
            ["éliminé"] = "eliminated",
            ["Duel : le chrono continue de tourner !"] = "Duel: the clock keeps running!",
            ["Abandonner le duel (défaite)"] = "Forfeit the duel (loss)",
            ["Renvoyer la course"] = "Send the run again",
            ["Nouveau duel"] = "New duel",
            ["Revoir le duel"] = "Watch the duel",
            ["Derniers duels"] = "Latest duels",
            ["Tes 10 derniers duels apparaîtront ici, à revoir des deux points de vue."] = "Your last 10 duels will show up here, to watch again from both sides.",
            ["Les 10 derniers, à revoir des deux points de vue. Les plus anciens laissent la place aux nouveaux."] = "The last 10, to watch again from both sides. The oldest make way for new ones.",
            ["En attente d'un adversaire"] = "Waiting for a rival",
            ["Momie anonyme"] = "Anonymous mummy",
            ["signalé"] = "reported",
            ["contre {0}"] = "vs {0}",
            ["V"] = "W",
            ["{0} V"] = "{0} W",
            ["{0} N"] = "{0} D",
            ["{0} D"] = "{0} L",
            ["N"] = "D",
            ["D"] = "L",
            ["TOI"] = "YOU",
            ["RIVAL"] = "RIVAL",
            ["MORT"] = "DEAD",
            ["SORTI · {0}"] = "OUT · {0}",
            ["TEMPS ÉCOULÉ"] = "TIME'S UP",
            ["ABANDON"] = "FORFEIT",
            ["{0} coups"] = "{0} moves",
            ["Personne n'a encore couru contre ton fantôme : le duel se complétera quand un adversaire l'aura affronté."] = "Nobody has raced your ghost yet: the duel will be completed once a rival has.",
            ["Duel joué sur une ancienne version du jeu : il ne peut plus être rejoué."] = "Duel played on an older version of the game: it can no longer be replayed.",
            ["Ce duel ne peut pas être rejoué."] = "This duel cannot be replayed.",
            ["Duel en attente d'un adversaire"] = "Duel waiting for a rival",
            ["Victoire"] = "Win",
            ["Match nul"] = "Draw",
            ["Défaite"] = "Loss",
            ["Signaler {0} pour triche ?"] = "Report {0} for cheating?",
            ["Le duel entier, vos deux courses, sera transmis à l'équipe qui l'examinera. Aucune sanction n'est automatique."] = "The whole duel, both of your runs, will be sent to the team for review. No penalty is ever automatic.",
            ["Signaler"] = "Report",
            ["Envoi impossible : vérifie ta connexion."] = "Could not send: check your connection.",
            ["Merci : le duel sera examiné."] = "Thanks: the duel will be reviewed.",
            ["Tu as déjà envoyé {0} signalements aujourd'hui."] = "You have already sent {0} reports today.",
            ["Personne à signaler sur ce duel."] = "Nobody to report in this duel.",
            ["Ce duel n'est plus sur le serveur."] = "This duel is no longer on the server.",
            ["Touche pour passer"] = "Tap to skip",
            ["Personne… encore"] = "Nobody… yet",
            ["Ta course deviendra le fantôme du prochain challenger"] = "Your run will become the next challenger's ghost",
            ["Retour aux duels"] = "Back to duels",
            ["contre {0} · Elo {1}"] = "against {0} · Elo {1}",
            ["Premier sur ce tombeau"] = "First on this tomb",
            ["mort à {0} % du chemin ({1})"] = "died {0}% of the way ({1})",
            ["temps écoulé, {0} % du chemin"] = "time's up, {0}% of the way",
            ["abandon"] = "forfeit",
            ["Verdict des dieux…"] = "The gods' verdict…",
            ["Le serveur rejoue ta course."] = "The server is replaying your run.",
            ["Envoi impossible"] = "Could not send",
            ["Vérifie ta connexion : le duel reste ouvert 10 minutes."] = "Check your connection: the duel stays open for 10 minutes.",
            ["VICTOIRE !"] = "VICTORY!",
            ["MATCH NUL"] = "DRAW",
            ["DÉFAITE"] = "DEFEAT",
            ["COURSE ENREGISTRÉE"] = "RUN RECORDED",
            ["Personne n'attendait sur ce tombeau : ta course devient le fantôme du prochain challenger. Ton Elo bougera à ce moment-là."] = "Nobody was waiting on this tomb: your run becomes the next challenger's ghost. Your Elo will move then.",
            ["Balance de Maât"] = "Scales of Maat",
            ["Plume de Maât"] = "Feather of Maat",
            ["Chacal d'obsidienne"] = "Obsidian jackal",
            ["Bastet des étoiles"] = "Starry Bastet",
            ["Momie de diamant"] = "Diamond mummy",
            ["Élu de Maât · {0}"] = "Chosen of Maat · {0}",
            ["{0} · {1}"] = "{0} · {1}",
            ["Flambeau du centurion"] = "Centurion's flame",
            ["Plasma du duelliste"] = "Duelist's plasma",
            ["Lanterne de l'arène"] = "Arena lantern",
            ["Sceptre du challenger"] = "Challenger's sceptre",

            // Bottom bar and saved replays
            ["Solo"] = "Solo",
            ["Quitter Mummy Escape ?"] = "Quit Mummy Escape?",
            ["Ta progression est enregistrée."] = "Your progress is saved.",
            ["Replays enregistrés ({0}/{1})"] = "Saved replays ({0}/{1})",
            ["Les 10 places sont prises : touche le replay à remplacer."] = "All 10 slots are taken: tap the replay to replace.",
            ["Enregistre un duel (+) pour le garder : il restera ici tant que tu ne le remplaces pas."] = "Save a duel (+) to keep it: it stays here until you replace it.",
            ["Gardés tant que tu ne les remplaces pas."] = "Kept until you replace them.",
            ["Remplacer"] = "Replace",
        };
    }
}
