using System.Collections.Generic;

namespace MummyEscape
{
    public static partial class Loc
    {
        /// <summary>English, keyed by the French text. Placeholders ({0}) and rich-text tags must be kept.</summary>
        static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            // ---------------------------------------------------------------- menu, shop, settings
            ["MUMMY\nESCAPE"] = "MUMMY\nESCAPE",
            ["MUMMY ESCAPE"] = "MUMMY ESCAPE",
            ["Échappe-toi du tombeau… à l'aveugle."] = "Escape the tomb… in the dark.",
            ["JOUER"] = "PLAY",
            ["Classement"] = "Leaderboard",
            ["Amis"] = "Friends",
            ["Boutique"] = "Shop",
            ["Paramètres"] = "Settings",
            ["Quitter"] = "Quit",
            ["Étoiles : {0}"] = "Stars: {0}",
            ["Scarabées : {0}"] = "Scarabs: {0}",
            ["Compte {0} · {1}"] = "Account {0} · {1}",
            ["Invité : {0}"] = "Guest: {0}",
            ["Gagne des scarabées en décrochant de nouvelles étoiles."] = "Earn scarabs by winning new stars.",
            ["{0} scarabées"] = "{0} scarabs",
            ["Équipé"] = "Equipped",
            ["Équiper"] = "Equip",
            ["Son"] = "Sound",
            ["Musique"] = "Music",
            ["Effets sonores"] = "Sound effects",
            ["Image"] = "Display",
            ["Luminosité"] = "Brightness",
            ["normale"] = "normal",
            ["Effets lumineux avancés"] = "Advanced lighting effects",
            ["Tremblements d'écran"] = "Screen shake",
            ["Confort et compte"] = "Comfort and account",
            ["Vibrations"] = "Vibrations",
            ["Mon compte"] = "My account",
            ["Confidentialité"] = "Privacy",
            ["générateur v{0}"] = "generator v{0}",
            ["Langue"] = "Language",
            ["Automatique (langue du téléphone)"] = "Automatic (phone language)",
            ["Langue : automatique ({0})"] = "Language: automatic ({0})",
            ["Langue : {0}"] = "Language: {0}",
            ["Annuler"] = "Cancel",

            // ---------------------------------------------------------------- level select, acts, skins
            ["Choisis ta crypte"] = "Choose your crypt",
            ["Acte {0}"] = "Act {0}",
            ["{0} étage"] = "{0} floor",
            ["{0} étages"] = "{0} floors",
            ["{0} à {1} étages"] = "{0} to {1} floors",
            ["Évadé"] = "Escaped",
            ["Inexploré"] = "Unexplored",
            ["L'Antichambre"] = "The Antechamber",
            ["Les Galeries inondées"] = "The Flooded Galleries",
            ["Les Ruines effondrées"] = "The Collapsed Ruins",
            ["La Cité d'Anubis"] = "The City of Anubis",
            ["Le Sanctuaire embrasé"] = "The Blazing Sanctuary",
            ["Un tombeau intact, scellé depuis trois mille ans."] = "An untouched tomb, sealed for three thousand years.",
            ["Le Nil a envahi les galeries : les courants emportent tout."] = "The Nile has flooded the galleries: the currents sweep everything away.",
            ["Les voûtes s'effondrent : chaque dalle peut céder."] = "The vaults are collapsing: any slab may give way.",
            ["Une cité d'Anubis venue d'un autre âge : lasers et portails."] = "A city of Anubis from another age: lasers and portals.",
            ["Le sanctuaire brûle : les flammes jaillissent en rythme."] = "The sanctuary is burning: flames burst out in rhythm.",
            ["Momie du Nil"] = "Nile Mummy",
            ["Pharaon doré"] = "Golden Pharaoh",
            ["Ombre d'Anubis"] = "Shadow of Anubis",
            ["Momie de jade"] = "Jade Mummy",
            ["Gardien lapis"] = "Lapis Guardian",
            ["Scarabée sacré"] = "Sacred Scarab",

            // ---------------------------------------------------------------- in game
            ["Carte"] = "Map",
            ["Prêt"] = "Ready",
            ["Niveau {0}"] = "Level {0}",
            ["Les dieux scellent un nouveau tombeau…"] = "The gods are sealing a new tomb…",
            ["Coups : {0}"] = "Moves: {0}",
            ["Étage {0} / {1}"] = "Floor {0} / {1}",
            ["{0} étages empilés, le 1er en bas"] = "{0} stacked floors, the 1st at the bottom",
            ["Acte {0} — {1}"] = "Act {0} — {1}",
            ["Mémorise le tombeau !"] = "Memorize the tomb!",
            ["Enregistrement d'écran détecté :\nle tombeau reste dans l'ombre"] = "Screen recording detected:\nthe tomb stays in the dark",
            ["Capture d'écran : les dieux ont scellé\nun autre tombeau !"] = "Screenshot: the gods have sealed\nanother tomb!",
            ["Aveuglé ! ({0})"] = "Blinded! ({0})",
            ["Torche éteinte : longe une torche murale"] = "Torch out: walk past a wall torch",
            ["Glisse pour avancer d'une case.\nTa torche éclaire les cases voisines."] = "Swipe to move one tile.\nYour torch lights up the tiles around you.",
            ["Maintiens « Carte » pour revoir ce que tu as exploré."] = "Hold \"Map\" to review what you have explored.",
            ["Les courants t'emportent jusqu'au bout\net ne se remontent pas."] = "Currents carry you all the way\nand cannot be walked against.",
            ["Les dalles fissurées s'effondrent\ndès que tu les quittes."] = "Cracked slabs collapse\nas soon as you step off them.",
            ["Un levier inverse les barrières :\nrouges ouvertes, bleues fermées."] = "A lever swaps the barriers:\nred open, blue closed.",
            ["Les jets de flammes crachent un pas sur trois :\nobserve leur rythme."] = "Flame jets fire every third step:\nwatch their rhythm.",
            ["Pause"] = "Pause",
            ["Reprendre"] = "Resume",
            ["Recommencer"] = "Restart",
            ["Quitter le niveau"] = "Quit level",

            // ---------------------------------------------------------------- end of level, scores
            ["ÉVADÉ !"] = "ESCAPED!",
            ["EMMURÉE !"] = "WALLED IN!",
            ["LA MOMIE A PÉRI"] = "THE MUMMY PERISHED",
            ["Chemin parfait !"] = "Perfect path!",
            ["<b>+{0}</b> coup de plus que le chemin idéal"] = "<b>+{0}</b> move more than the ideal path",
            ["<b>+{0}</b> coups de plus que le chemin idéal"] = "<b>+{0}</b> moves more than the ideal path",
            ["Réessaie : un nouveau tombeau t'attend."] = "Try again: a new tomb awaits you.",
            ["Évadé en <b>{0}</b> coups · <b>{1}</b>"] = "Escaped in <b>{0}</b> moves · <b>{1}</b>",
            ["<b>{0}</b> interaction"] = "<b>{0}</b> interaction",
            ["<b>{0}</b> interactions"] = "<b>{0}</b> interactions",
            ["{0} interaction"] = "{0} interaction",
            ["{0} interactions"] = "{0} interactions",
            ["<b>{0}</b>/{1} PV"] = "<b>{0}</b>/{1} HP",
            ["Plus aucune issue : la momie est emmurée après {0} coups."] = "No way out left: the mummy is walled in after {0} moves.",
            ["Courants, dalles effondrées et barrières ne pardonnent pas."] = "Currents, collapsed slabs and barriers are unforgiving.",
            ["Les pièges ont eu raison de toi après {0} coups."] = "The traps got the better of you after {0} moves.",
            ["Nouveau record ! ({0} → {1})"] = "New record! ({0} → {1})",
            ["Premier passage !"] = "First clear!",
            ["+{0} scarabées"] = "+{0} scarabs",
            ["Partager"] = "Share",
            ["Niveau suivant"] = "Next level",
            ["Rejouer"] = "Play again",
            ["Menu"] = "Menu",
            ["parfait"] = "perfect",
            ["+{0} coup"] = "+{0} move",
            ["+{0} coups"] = "+{0} moves",
            ["Évadé en {0} coups, {1} ({2})"] = "Escaped in {0} moves, {1} ({2})",
            ["{0} interactions · {1}/{2} PV restants"] = "{0} interactions · {1}/{2} HP left",
            ["Feras-tu mieux ? {0}"] = "Can you do better? {0}",
            ["Partager mon évasion"] = "Share my escape",

            // ---------------------------------------------------------------- leaderboard
            ["Monde"] = "World",
            ["Pays"] = "Country",
            ["Chargement…"] = "Loading…",
            ["Choisis ton pays dans Amis › Profil."] = "Choose your country in Friends › Profile.",
            ["Top 100 mondial"] = "Global top 100",
            ["Top 100 · {0}"] = "Top 100 · {0}",
            ["Toi et tes amis"] = "You and your friends",
            ["démo hors ligne"] = "offline demo",
            ["hors ligne"] = "offline",
            ["{0}  (toi)"] = "{0}  (you)",
            ["Ton record : {0} (pas encore classé)"] = "Your record: {0} (not ranked yet)",
            ["Termine ce niveau pour entrer au classement"] = "Finish this level to enter the leaderboard",

            // ---------------------------------------------------------------- friends
            ["Mon nom"] = "My name",
            ["Demandes"] = "Requests",
            ["+  Ajouter un ami"] = "+  Add a friend",
            ["Ton code ami : donne-le à tes amis"] = "Your friend code: give it to your friends",
            ["Démo hors ligne (amis fictifs)"] = "Offline demo (fictional friends)",
            ["Hors ligne"] = "Offline",
            ["Pays ?"] = "Country?",
            ["Pays : {0}"] = "Country: {0}",
            ["Les amis font partie du mode en ligne : Paramètres › Confidentialité."] = "Friends are part of online mode: Settings › Privacy.",
            ["Amis ({0})"] = "Friends ({0})",
            ["Demandes ({0})"] = "Requests ({0})",
            ["Aucun ami pour l'instant.\nPartage ton code pour qu'on t'ajoute !"] = "No friends yet.\nShare your code so people can add you!",
            ["Aucune demande en attente."] = "No pending requests.",
            ["En ligne"] = "Online",
            ["progression non partagée"] = "progress not shared",
            ["niveau {0} · {1} étoiles"] = "level {0} · {1} stars",
            ["veut devenir ton ami"] = "wants to be your friend",
            ["Refuser"] = "Decline",
            ["Accepter"] = "Accept",
            ["Ton nom de momie"] = "Your mummy name",
            ["Visible dans les classements.\nN'utilise pas ton vrai nom."] = "Shown in the leaderboards.\nDon't use your real name.",
            ["Nom"] = "Name",
            ["Enregistrer"] = "Save",
            ["3 caractères minimum."] = "3 characters minimum.",
            ["Ajouter un ami"] = "Add a friend",
            ["Demande-lui son code ami\n(exemple : Nefertari#2041)."] = "Ask for their friend code\n(example: Nefertari#2041).",
            ["Code ami"] = "Friend code",
            ["Inviter"] = "Invite",
            ["Le code contient un # suivi de 4 chiffres."] = "The code contains a # followed by 4 digits.",
            ["Joueur introuvable."] = "Player not found.",
            ["Ajoute-moi sur Mummy Escape ! Mon code ami : {0}"] = "Add me on Mummy Escape! My friend code: {0}",
            ["le plus loin"] = "furthest",
            ["étoiles"] = "stars",
            ["Niveau"] = "Level",
            ["Ami"] = "Friend",
            ["Toi"] = "You",
            ["/ toi {0}"] = "/ you {0}",
            ["Retirer des amis"] = "Remove friend",
            ["Progression non partagée pour l'instant."] = "Progress not shared yet.",
            ["Confirmer le retrait ?"] = "Confirm removal?",
            ["Momie"] = "Mummy",

            // ---------------------------------------------------------------- country
            ["Ton pays"] = "Your country",
            ["Affiché à côté de tes scores et utilisé pour le classement « Pays ».\nFacultatif : tu peux le retirer à tout moment."] =
                "Shown next to your scores and used for the \"Country\" leaderboard.\nOptional: you can remove it at any time.",
            ["Ne pas afficher"] = "Don't show",
            ["par défaut"] = "default",
            ["Pays de l'appareil"] = "Device country",
            ["inconnu"] = "unknown",
            ["Inconnu"] = "Unknown",
            ["Afrique du Sud"] = "South Africa", ["Algérie"] = "Algeria", ["Allemagne"] = "Germany",
            ["Arabie saoudite"] = "Saudi Arabia", ["Argentine"] = "Argentina", ["Australie"] = "Australia",
            ["Autriche"] = "Austria", ["Belgique"] = "Belgium", ["Bénin"] = "Benin",
            ["Brésil"] = "Brazil", ["Burkina Faso"] = "Burkina Faso", ["Cameroun"] = "Cameroon",
            ["Canada"] = "Canada", ["Chili"] = "Chile", ["Chine"] = "China",
            ["Colombie"] = "Colombia", ["Corée du Sud"] = "South Korea", ["Côte d'Ivoire"] = "Côte d'Ivoire",
            ["Danemark"] = "Denmark", ["Égypte"] = "Egypt", ["Émirats arabes unis"] = "United Arab Emirates",
            ["Espagne"] = "Spain", ["États-Unis"] = "United States", ["Finlande"] = "Finland",
            ["France"] = "France", ["Gabon"] = "Gabon", ["Grèce"] = "Greece",
            ["Haïti"] = "Haiti", ["Hongrie"] = "Hungary", ["Inde"] = "India",
            ["Indonésie"] = "Indonesia", ["Irlande"] = "Ireland", ["Israël"] = "Israel",
            ["Italie"] = "Italy", ["Japon"] = "Japan", ["Liban"] = "Lebanon",
            ["Luxembourg"] = "Luxembourg", ["Madagascar"] = "Madagascar", ["Mali"] = "Mali",
            ["Maroc"] = "Morocco", ["Mexique"] = "Mexico", ["Monaco"] = "Monaco",
            ["Norvège"] = "Norway", ["Nouvelle-Zélande"] = "New Zealand", ["Pays-Bas"] = "Netherlands",
            ["Pérou"] = "Peru", ["Philippines"] = "Philippines", ["Pologne"] = "Poland",
            ["Portugal"] = "Portugal", ["RD Congo"] = "DR Congo", ["Roumanie"] = "Romania",
            ["Royaume-Uni"] = "United Kingdom", ["Sénégal"] = "Senegal", ["Suède"] = "Sweden",
            ["Suisse"] = "Switzerland", ["Thaïlande"] = "Thailand", ["Tunisie"] = "Tunisia",
            ["Turquie"] = "Turkey", ["Ukraine"] = "Ukraine", ["Viêt Nam"] = "Vietnam",

            // ---------------------------------------------------------------- first launch, privacy
            ["Conditions"] = "Terms",
            ["Avant de jouer"] = "Before you play",
            ["Mummy Escape se joue sans connexion : dans ce mode, rien ne quitte ton téléphone.\n\n" +
             "Le mode en ligne ajoute les classements, les amis et un compte facultatif pour retrouver ta progression sur un autre appareil. " +
             "Il envoie alors à notre prestataire (Unity) un identifiant aléatoire, ton pseudonyme et tes scores.\n\n" +
             "Ni publicité, ni pistage, ni adresse e-mail."] =
                "Mummy Escape can be played without a connection: in that mode, nothing leaves your phone.\n\n" +
                "Online mode adds leaderboards, friends and an optional account to restore your progress on another device. " +
                "It then sends our provider (Unity) a random ID, your nickname and your scores.\n\n" +
                "No ads, no tracking, no email address.",
            ["Jouer en ligne"] = "Play online",
            ["Jouer hors ligne"] = "Play offline",
            ["Tu peux changer d'avis à tout moment dans Paramètres › Confidentialité."] = "You can change your mind at any time in Settings › Privacy.",
            ["Ton année de naissance"] = "Your year of birth",
            ["Elle sert seulement à savoir si l'accord d'un parent est nécessaire. Elle n'est ni conservée, ni envoyée."] =
                "It is only used to know whether a parent's consent is needed. It is neither kept nor sent.",
            ["AAAA"] = "YYYY",
            ["J'accepte les conditions d'utilisation"] = "I accept the terms of use",
            ["Lire les conditions"] = "Read the terms",
            ["Lire la confidentialité"] = "Read the privacy policy",
            ["Retour"] = "Back",
            ["Continuer"] = "Continue",
            ["Indique une année valide (4 chiffres)."] = "Enter a valid year (4 digits).",
            ["Accepte les conditions pour jouer en ligne."] = "Accept the terms to play online.",
            ["Demande à un parent"] = "Ask a parent",
            ["Pour jouer en ligne à ton âge, l'accord d'un parent ou d'un tuteur est nécessaire.\n\n" +
             "À l'attention du parent : le mode en ligne publie un pseudonyme (attribué au hasard, modifiable) et les scores de votre enfant, " +
             "et lui permet d'ajouter des amis par leur code. Aucune adresse e-mail, aucun nom réel, aucune publicité. " +
             "Vous pouvez retirer cet accord et supprimer ses données à tout moment dans Paramètres › Confidentialité."] =
                "To play online at your age, a parent's or guardian's consent is required.\n\n" +
                "For the parent: online mode publishes a nickname (randomly assigned, editable) and your child's scores, " +
                "and lets them add friends by their code. No email address, no real name, no ads. " +
                "You can withdraw this consent and delete their data at any time in Settings › Privacy.",
            ["Lire la politique de confidentialité"] = "Read the privacy policy",
            ["Parent ou tuteur : votre année de naissance"] = "Parent or guardian: your year of birth",
            ["Je suis son parent ou tuteur et j'autorise"] = "I am their parent or guardian and I consent",
            ["Autoriser"] = "Allow",
            ["L'accord doit venir d'un adulte."] = "Consent must come from an adult.",
            ["Cochez la case pour confirmer votre accord."] = "Tick the box to confirm your consent.",
            ["Mode en ligne"] = "Online mode",
            ["Classements, amis, compte"] = "Leaderboards, friends, account",
            ["État : en ligne ({0})"] = "Status: online ({0})",
            ["État : {0}"] = "Status: {0}",
            ["Retirer l'autorisation parentale"] = "Withdraw parental consent",
            ["Mes amis voient ma progression"] = "My friends see my progress",
            ["non affiché"] = "not shown",
            ["celui de l'appareil"] = "the device's",
            ["Pays dans les classements : {0}"] = "Country in leaderboards: {0}",
            ["Mes données"] = "My data",
            ["Exporter mes données"] = "Export my data",
            ["Supprimer mes données en ligne"] = "Delete my online data",
            ["Effacer les données de ce téléphone"] = "Erase the data on this phone",
            ["Informations"] = "Information",
            ["Ni publicité, ni mesure d'audience, ni traceur, ni adresse e-mail."] = "No ads, no analytics, no trackers, no email address.",
            ["Politique de confidentialité"] = "Privacy policy",
            ["Conditions d'utilisation"] = "Terms of use",
            ["Contacter l'éditeur"] = "Contact the publisher",
            ["Une réclamation ? Tu peux saisir la CNIL (cnil.fr) ou l'autorité de ton pays."] =
                "A complaint? You can contact the CNIL (cnil.fr) or the authority of your country.",
            ["Ton dernier choix : {0} (politique v{1})."] = "Your last choice: {0} (policy v{1}).",
            ["compte {0}"] = "account {0}",
            ["invité"] = "guest",
            ["Supprimer mes données en ligne ?"] = "Delete my online data?",
            ["Ton profil, ton compte, ton pseudonyme, tes scores, tes amis et ta sauvegarde en ligne seront définitivement effacés. " +
             "Le mode en ligne sera désactivé. Ta progression sur ce téléphone est conservée."] =
                "Your profile, account, nickname, scores, friends and online backup will be permanently erased. " +
                "Online mode will be turned off. Your progress on this phone is kept.",
            ["Supprimer"] = "Delete",
            ["Effacer ce téléphone ?"] = "Erase this phone?",
            ["Ta progression, tes scarabées, tes apparences et tes choix enregistrés sur ce téléphone seront effacés. " +
             "Tes données en ligne ne sont pas touchées (supprime-les d'abord si tu le souhaites)."] =
                "Your progress, scarabs, skins and choices saved on this phone will be erased. " +
                "Your online data is not affected (delete it first if you wish).",
            ["Effacer"] = "Erase",

            // ---------------------------------------------------------------- account
            ["Compte"] = "Account",
            ["Mode hors ligne"] = "Offline mode",
            ["Le compte fait partie du mode en ligne. Active-le dans Confidentialité pour créer un compte ou te connecter."] =
                "The account is part of online mode. Turn it on in Privacy to create an account or sign in.",
            ["Connecté"] = "Signed in",
            ["Identifiant : {0}\nPseudonyme public : {1}"] = "Login: {0}\nPublic nickname: {1}",
            ["Ta progression est sauvegardée en ligne : connecte-toi avec ce compte sur un autre appareil pour la retrouver."] =
                "Your progress is backed up online: sign in with this account on another device to get it back.",
            ["Changer le mot de passe"] = "Change password",
            ["Se déconnecter"] = "Sign out",
            ["Supprimer mon compte"] = "Delete my account",
            ["Tu joues en invité"] = "You are playing as a guest",
            ["Ta progression n'existe que sur ce téléphone. Crée un compte pour la sauvegarder et la retrouver ailleurs : " +
             "il suffit d'un identifiant et d'un mot de passe, sans adresse e-mail."] =
                "Your progress only exists on this phone. Create an account to back it up and find it elsewhere: " +
                "all it takes is a login and a password, no email address.",
            ["Créer un compte"] = "Create an account",
            ["Non connecté"] = "Not signed in",
            ["Continuer en invité"] = "Continue as a guest",
            ["J'ai déjà un compte"] = "I already have an account",
            ["Sans e-mail, un mot de passe oublié ne peut pas être récupéré : note-le bien."] =
                "Without an email, a forgotten password cannot be recovered: write it down.",
            ["Identifiant : {0}-{1} caractères (lettres, chiffres, . - _ @)."] = "Login: {0}-{1} characters (letters, digits, . - _ @).",
            ["Mot de passe : {0}-{1} caractères, majuscule, minuscule, chiffre et symbole."] =
                "Password: {0}-{1} characters, uppercase, lowercase, digit and symbol.",
            ["Identifiant"] = "Login",
            ["Mot de passe"] = "Password",
            ["Confirme le mot de passe"] = "Confirm the password",
            ["Créer"] = "Create",
            ["Les deux mots de passe diffèrent."] = "The two passwords don't match.",
            ["Se connecter"] = "Sign in",
            ["La progression de ce téléphone sera ajoutée à celle du compte."] = "This phone's progress will be added to the account's.",
            ["Connexion"] = "Sign in",
            ["Remplis les deux champs."] = "Fill in both fields.",
            ["Mot de passe actuel"] = "Current password",
            ["Nouveau mot de passe"] = "New password",
            ["Confirme le nouveau"] = "Confirm the new one",
            ["Changer"] = "Change",
            ["Identifiant : {0} à {1} caractères."] = "Login: {0} to {1} characters.",
            ["Identifiant : lettres, chiffres et . - _ @ uniquement (sans accents ni espaces)."] =
                "Login: letters, digits and . - _ @ only (no accents or spaces).",
            ["Mot de passe : {0} à {1} caractères."] = "Password: {0} to {1} characters.",
            ["Mot de passe : au moins une majuscule, une minuscule, un chiffre et un symbole."] =
                "Password: at least one uppercase letter, one lowercase letter, one digit and one symbol.",

            // ---------------------------------------------------------------- online statuses and errors
            ["Hors ligne (autorisation parentale requise pour jouer en ligne)"] = "Offline (parental consent required to play online)",
            ["Hors ligne (mode en ligne désactivé dans Confidentialité)"] = "Offline (online mode turned off in Privacy)",
            ["Déconnecté (Paramètres › Compte pour te reconnecter)"] = "Signed out (Settings › Account to sign back in)",
            ["Connexion impossible : {0}"] = "Cannot connect: {0}",
            ["Données en ligne supprimées — mode hors ligne"] = "Online data deleted — offline mode",
            ["Hors ligne — configure Unity Gaming Services pour les classements et les amis."] =
                "Offline — set up Unity Gaming Services for leaderboards and friends.",
            ["Les comptes nécessitent une connexion à Unity Gaming Services."] = "Accounts require a connection to Unity Gaming Services.",
            ["Identifiant ou mot de passe incorrect."] = "Wrong login or password.",
            ["Mot de passe actuel incorrect."] = "Wrong current password.",
            ["Connexion…"] = "Connecting…",
            ["Hors ligne (projet non lié à Unity Gaming Services)"] = "Offline (project not linked to Unity Gaming Services)",
            ["Hors ligne ({0})"] = "Offline ({0})",
            ["Ce joueur a déjà un compte."] = "This player already has an account.",
            ["Cet identifiant est déjà pris ou invalide."] = "This login is already taken or invalid.",
            ["Déconnecté"] = "Signed out",
            ["Compte supprimé"] = "Account deleted",
            ["La suppression a échoué, réessaie plus tard."] = "Deletion failed, try again later.",
            ["Connexion impossible. Vérifie ton accès à Internet."] = "Cannot connect. Check your Internet access.",
            ["Trop de tentatives, réessaie dans quelques minutes."] = "Too many attempts, try again in a few minutes.",
        };
    }
}
